// AUTO-GENERATED by the Day 33 pack script — VO line index by key.
export const K = {
 "why": 0,
 "guess": 1,
 "good": 2,
 "around": 3,
 "tilt": 4,
 "say": 5,
 "leo_say": 6,
 "lean_in": 7,
 "lean_out": 8,
 "between": 9,
 "lean_turn": 10,
 "torch": 11,
 "see": 12,
 "leo_wow": 13,
 "other": 14,
 "recap": 15,
 "r1": 16,
 "r2": 17,
 "r3": 18,
 "wow": 19,
 "end": 20
} as const;
