// AUTO-GENERATED by the Day 10 pack script — line indices into VO.
export const PLAN = {
 "colors": [
  {
   "en": "Red",
   "fr": "rouge",
   "hex": "#e63946",
   "obj": "apple",
   "en1": 2,
   "en2": 3,
   "fr1": 4,
   "fr2": 5,
   "say": 6
  },
  {
   "en": "Orange",
   "fr": "orange",
   "hex": "#ff8c1a",
   "obj": "orange",
   "en1": 7,
   "en2": 8,
   "fr1": 9,
   "fr2": 10,
   "say": 11
  },
  {
   "en": "Yellow",
   "fr": "jaune",
   "hex": "#ffd60a",
   "obj": "sun",
   "en1": 12,
   "en2": 13,
   "fr1": 14,
   "fr2": 15,
   "say": 16
  },
  {
   "en": "Green",
   "fr": "vert",
   "hex": "#52b788",
   "obj": "frog",
   "en1": 17,
   "en2": 18,
   "fr1": 19,
   "fr2": 20,
   "say": 21
  },
  {
   "en": "Blue",
   "fr": "bleu",
   "hex": "#1d72d8",
   "obj": "balloon",
   "en1": 22,
   "en2": 23,
   "fr1": 24,
   "fr2": 25,
   "say": 26
  },
  {
   "en": "Purple",
   "fr": "violet",
   "hex": "#7b2cbf",
   "obj": "grapes",
   "en1": 30,
   "en2": 31,
   "fr1": 32,
   "fr2": 33,
   "say": 34
  },
  {
   "en": "Pink",
   "fr": "rose",
   "hex": "#ff8fab",
   "obj": "pig",
   "en1": 35,
   "en2": 36,
   "fr1": 37,
   "fr2": 38,
   "say": 39
  },
  {
   "en": "Brown",
   "fr": "marron",
   "hex": "#8d5a3b",
   "obj": "bear",
   "en1": 40,
   "en2": 41,
   "fr1": 42,
   "fr2": 43,
   "say": 44
  },
  {
   "en": "Black",
   "fr": "noir",
   "hex": "#2b2d42",
   "obj": "cat",
   "en1": 45,
   "en2": 46,
   "fr1": 47,
   "fr2": 48,
   "say": 49
  },
  {
   "en": "White",
   "fr": "blanc",
   "hex": "#ffffff",
   "obj": "cloud",
   "en1": 50,
   "en2": 51,
   "fr1": 52,
   "fr2": 53,
   "say": 54
  },
  {
   "en": "Gray",
   "fr": "gris",
   "hex": "#9aa0a6",
   "obj": "mouse",
   "en1": 58,
   "en2": 59,
   "fr1": 60,
   "fr2": 61,
   "say": 62
  },
  {
   "en": "Gold",
   "fr": "doré",
   "hex": "#e9b824",
   "obj": "star",
   "en1": 63,
   "en2": 64,
   "fr1": 65,
   "fr2": 66,
   "say": 67
  },
  {
   "en": "Silver",
   "fr": "argenté",
   "hex": "#c0c7d0",
   "obj": "key",
   "en1": 68,
   "en2": 69,
   "fr1": 70,
   "fr2": 71,
   "say": 72
  },
  {
   "en": "Turquoise",
   "fr": "turquoise",
   "hex": "#2ec4b6",
   "obj": "fish",
   "en1": 73,
   "en2": 74,
   "fr1": 75,
   "fr2": 76,
   "say": 77
  },
  {
   "en": "Sky blue",
   "fr": "bleu ciel",
   "hex": "#87cefa",
   "obj": "sky",
   "en1": 78,
   "en2": 79,
   "fr1": 80,
   "fr2": 81,
   "say": 82
  },
  {
   "en": "Lime green",
   "fr": "vert citron",
   "hex": "#a7d129",
   "obj": "leaf",
   "en1": 86,
   "en2": 87,
   "fr1": 88,
   "fr2": 89,
   "say": 90
  },
  {
   "en": "Navy blue",
   "fr": "bleu marine",
   "hex": "#1d3557",
   "obj": "boat",
   "en1": 91,
   "en2": 92,
   "fr1": 93,
   "fr2": 94,
   "say": 95
  },
  {
   "en": "Peach",
   "fr": "pêche",
   "hex": "#ffb38a",
   "obj": "peach",
   "en1": 96,
   "en2": 97,
   "fr1": 98,
   "fr2": 99,
   "say": 100
  },
  {
   "en": "Lavender",
   "fr": "lavande",
   "hex": "#b8a1e3",
   "obj": "flower",
   "en1": 101,
   "en2": 102,
   "fr1": 103,
   "fr2": 104,
   "say": 105
  },
  {
   "en": "Beige",
   "fr": "beige",
   "hex": "#e8d8b8",
   "obj": "cookie",
   "en1": 106,
   "en2": 107,
   "fr1": 108,
   "fr2": 109,
   "say": 110
  }
 ],
 "quiz": [
  {
   "target": 3,
   "options": [
    0,
    3,
    4
   ],
   "correct": 1,
   "ask": 27,
   "ans": 28,
   "ansFr": 29
  },
  {
   "target": 6,
   "options": [
    5,
    6,
    8
   ],
   "correct": 1,
   "ask": 55,
   "ans": 56,
   "ansFr": 57
  },
  {
   "target": 11,
   "options": [
    10,
    11,
    12
   ],
   "correct": 1,
   "ask": 83,
   "ans": 84,
   "ansFr": 85
  },
  {
   "target": 17,
   "options": [
    16,
    17,
    18
   ],
   "correct": 1,
   "ask": 111,
   "ans": 112,
   "ansFr": 113
  }
 ],
 "recapEn": [
  115,
  116,
  117,
  118
 ],
 "recapFr": [
  120,
  121,
  122,
  123
 ],
 "bye": 124,
 "byeBobo": 125
} as const;
