// AUTO-GENERATED by the Day 19 pack script — VO line index by key.
export const K = {
 "why": 0,
 "guess": 1,
 "good": 2,
 "nolight": 3,
 "sun": 4,
 "bounce": 5,
 "word": 6,
 "say": 7,
 "leo_say": 8,
 "torch": 9,
 "see": 10,
 "leo_wow": 11,
 "recap": 12,
 "r1": 13,
 "r2": 14,
 "r3": 15,
 "wow": 16,
 "end": 17
} as const;
