// AUTO-GENERATED by the Day 12 pack script — VO line index by key.
export const K = {
 "why": 0,
 "guess": 1,
 "good": 2,
 "star": 3,
 "say": 4,
 "leo_say": 5,
 "inside": 6,
 "energy": 7,
 "travel": 8,
 "leo_wow": 9,
 "safety": 10,
 "recap": 11,
 "r1": 12,
 "r2": 13,
 "r3": 14,
 "wow": 15,
 "end": 16
} as const;
