// AUTO-GENERATED by tools/gen_voice.py — do not edit.
// Word times are derived from the Kokoro audio's own pauses; captions + lip-sync follow them.
import type { VoLine } from '../../lib/shorts';

export const VO: VoLine[] = [
  { speaker: 'bobo', text: 'Woof woof! Who is in the doghouse?', start: 1.4, end: 3.17, words: [{ w: 'Woof', start: 1.43, end: 1.708 }, { w: 'woof!', start: 1.708, end: 1.987 }, { w: 'Who', start: 1.987, end: 2.209 }, { w: 'is', start: 2.209, end: 2.321 }, { w: 'in', start: 2.321, end: 2.488 }, { w: 'the', start: 2.488, end: 2.599 }, { w: 'doghouse?', start: 2.599, end: 3.1 }] },
  { speaker: 'mila', text: 'Puppies! Let\'s count them together!', start: 7.77, end: 9.71, words: [{ w: 'Puppies!', start: 7.81, end: 8.189 }, { w: 'Let\'s', start: 8.189, end: 8.505 }, { w: 'count', start: 8.505, end: 8.885 }, { w: 'them', start: 8.885, end: 9.137 }, { w: 'together!', start: 9.137, end: 9.58 }] },
  { speaker: 'mila', text: 'One!', start: 11.31, end: 12.12, words: [{ w: 'One!', start: 11.39, end: 11.98 }] },
  { speaker: 'mila', text: 'Two!', start: 13.42, end: 14.23, words: [{ w: 'Two!', start: 13.47, end: 14.08 }] },
  { speaker: 'mila', text: 'Three!', start: 15.53, end: 16.4, words: [{ w: 'Three!', start: 15.6, end: 16.24 }] },
  { speaker: 'mila', text: 'Four!', start: 17.7, end: 18.62, words: [{ w: 'Four!', start: 17.79, end: 18.44 }] },
  { speaker: 'mila', text: 'Five!', start: 19.92, end: 20.84, words: [{ w: 'Five!', start: 20.0, end: 20.69 }] },
  { speaker: 'mila', text: 'Six!', start: 22.14, end: 22.93, words: [{ w: 'Six!', start: 22.22, end: 22.82 }] },
  { speaker: 'mila', text: 'Seven!', start: 24.23, end: 25.08, words: [{ w: 'Seven!', start: 24.28, end: 24.94 }] },
  { speaker: 'mila', text: 'Eight!', start: 26.38, end: 27.18, words: [{ w: 'Eight!', start: 26.45, end: 27.08 }] },
  { speaker: 'mila', text: 'Nine!', start: 28.48, end: 29.37, words: [{ w: 'Nine!', start: 28.56, end: 29.27 }] },
  { speaker: 'mila', text: 'Ten!', start: 30.67, end: 31.48, words: [{ w: 'Ten!', start: 30.72, end: 31.35 }] },
  { speaker: 'mila', text: 'Ten cute puppies!', start: 33.28, end: 34.66, words: [{ w: 'Ten', start: 33.31, end: 33.62 }, { w: 'cute', start: 33.62, end: 34.085 }, { w: 'puppies!', start: 34.085, end: 34.55 }] },
  { speaker: 'bobo', text: 'Yawn... Two puppies are sleepy.', start: 37.06, end: 38.76, words: [{ w: 'Yawn...', start: 37.09, end: 37.402 }, { w: 'Two', start: 37.402, end: 37.652 }, { w: 'puppies', start: 37.652, end: 38.026 }, { w: 'are', start: 38.026, end: 38.213 }, { w: 'sleepy.', start: 38.213, end: 38.65 }] },
  { speaker: 'mila', text: 'They go to sleep in the basket. Shh!', start: 40.36, end: 43.06, words: [{ w: 'They', start: 40.52, end: 40.674 }, { w: 'go', start: 40.674, end: 40.88 }, { w: 'to', start: 40.88, end: 41.034 }, { w: 'sleep', start: 41.034, end: 41.343 }, { w: 'in', start: 41.343, end: 41.497 }, { w: 'the', start: 41.497, end: 41.6 }, { w: 'basket.', start: 41.6, end: 41.96 }, { w: 'Shh!', start: 42.11, end: 42.88 }] },
  { speaker: 'mila', text: 'How many puppies are still awake?', start: 44.46, end: 46.42, words: [{ w: 'How', start: 44.52, end: 44.767 }, { w: 'many', start: 44.767, end: 45.076 }, { w: 'puppies', start: 45.076, end: 45.446 }, { w: 'are', start: 45.446, end: 45.631 }, { w: 'still', start: 45.631, end: 45.94 }, { w: 'awake?', start: 45.94, end: 46.31 }] },
  { speaker: 'mila', text: 'Eight!', start: 51.42, end: 52.22, words: [{ w: 'Eight!', start: 51.49, end: 52.12 }] },
  { speaker: 'mila', text: 'Ten, take away two, is eight!', start: 53.82, end: 55.78, words: [{ w: 'Ten,', start: 53.84, end: 54.135 }, { w: 'take', start: 54.135, end: 54.504 }, { w: 'away', start: 54.504, end: 54.872 }, { w: 'two,', start: 54.872, end: 55.167 }, { w: 'is', start: 55.167, end: 55.315 }, { w: 'eight!', start: 55.315, end: 55.61 }] },
  { speaker: 'mila', text: 'Let\'s check! One, two, three, four, five, six, seven, eight!', start: 57.78, end: 61.14, words: [{ w: 'Let\'s', start: 57.82, end: 58.142 }, { w: 'check!', start: 58.142, end: 58.464 }, { w: 'One,', start: 58.464, end: 58.721 }, { w: 'two,', start: 58.721, end: 58.979 }, { w: 'three,', start: 58.979, end: 59.301 }, { w: 'four,', start: 59.301, end: 59.622 }, { w: 'five,', start: 59.622, end: 59.944 }, { w: 'six,', start: 59.944, end: 60.266 }, { w: 'seven,', start: 60.266, end: 60.652 }, { w: 'eight!', start: 60.652, end: 60.91 }] },
  { speaker: 'bobo', text: 'Woof woof! Great counting!', start: 62.94, end: 64.38, words: [{ w: 'Woof', start: 62.97, end: 63.247 }, { w: 'woof!', start: 63.247, end: 63.524 }, { w: 'Great', start: 63.524, end: 63.857 }, { w: 'counting!', start: 63.857, end: 64.3 }] },
];
