// AUTO-GENERATED by the Day 16 pack script — VO line index by key.
export const K = {
 "hook": 0,
 "go": 1,
 "c1": 2,
 "c2": 3,
 "c3": 4,
 "c4": 5,
 "c5": 6,
 "c6": 7,
 "c7": 8,
 "c8": 9,
 "c9": 10,
 "c10": 11,
 "ten": 12,
 "crunch": 13,
 "oops": 14,
 "ans": 15,
 "eq": 16,
 "check": 17,
 "yay": 18
} as const;
