// AUTO-GENERATED by tools/gen_voice.py — do not edit.
// Word times are derived from the Kokoro audio's own pauses; captions + lip-sync follow them.
import type { VoLine } from '../../lib/shorts';

export const VO: VoLine[] = [
  { speaker: 'bobo', text: 'I picked lots of apples! How many apples do I have?', start: 1.4, end: 4.47, words: [{ w: 'I', start: 1.43, end: 1.608 }, { w: 'picked', start: 1.608, end: 1.903 }, { w: 'lots', start: 1.903, end: 2.258 }, { w: 'of', start: 2.258, end: 2.377 }, { w: 'apples!', start: 2.377, end: 2.732 }, { w: 'How', start: 2.732, end: 2.968 }, { w: 'many', start: 2.968, end: 3.264 }, { w: 'apples', start: 3.264, end: 3.619 }, { w: 'do', start: 3.619, end: 3.856 }, { w: 'I', start: 3.856, end: 4.033 }, { w: 'have?', start: 4.033, end: 4.27 }] },
  { speaker: 'mila', text: 'Let\'s count them together!', start: 9.07, end: 10.66, words: [{ w: 'Let\'s', start: 9.18, end: 9.494 }, { w: 'count', start: 9.494, end: 9.87 }, { w: 'them', start: 9.87, end: 10.121 }, { w: 'together!', start: 10.121, end: 10.56 }] },
  { speaker: 'mila', text: 'One!', start: 12.26, end: 13.07, words: [{ w: 'One!', start: 12.34, end: 12.93 }] },
  { speaker: 'mila', text: 'Two!', start: 14.37, end: 15.18, words: [{ w: 'Two!', start: 14.42, end: 15.03 }] },
  { speaker: 'mila', text: 'Three!', start: 16.48, end: 17.35, words: [{ w: 'Three!', start: 16.55, end: 17.19 }] },
  { speaker: 'mila', text: 'Four!', start: 18.65, end: 19.57, words: [{ w: 'Four!', start: 18.74, end: 19.39 }] },
  { speaker: 'mila', text: 'Five!', start: 20.87, end: 21.79, words: [{ w: 'Five!', start: 20.95, end: 21.64 }] },
  { speaker: 'mila', text: 'Six!', start: 23.09, end: 23.88, words: [{ w: 'Six!', start: 23.17, end: 23.77 }] },
  { speaker: 'mila', text: 'Seven!', start: 25.18, end: 26.03, words: [{ w: 'Seven!', start: 25.23, end: 25.89 }] },
  { speaker: 'mila', text: 'Eight!', start: 27.33, end: 28.13, words: [{ w: 'Eight!', start: 27.4, end: 28.03 }] },
  { speaker: 'mila', text: 'Nine!', start: 29.43, end: 30.32, words: [{ w: 'Nine!', start: 29.51, end: 30.22 }] },
  { speaker: 'mila', text: 'Ten!', start: 31.62, end: 32.43, words: [{ w: 'Ten!', start: 31.67, end: 32.3 }] },
  { speaker: 'mila', text: 'Ten apples!', start: 34.23, end: 35.36, words: [{ w: 'Ten', start: 34.31, end: 34.686 }, { w: 'apples!', start: 34.686, end: 35.25 }] },
  { speaker: 'bobo', text: 'Mmm... crunch!', start: 37.96, end: 39.11, words: [{ w: 'Mmm...', start: 37.99, end: 38.564 }, { w: 'crunch!', start: 38.564, end: 39.01 }] },
  { speaker: 'mila', text: 'Bobo! Now, how many apples?', start: 40.31, end: 42.26, words: [{ w: 'Bobo!', start: 40.34, end: 40.841 }, { w: 'Now,', start: 40.841, end: 41.127 }, { w: 'how', start: 41.127, end: 41.413 }, { w: 'many', start: 41.413, end: 41.771 }, { w: 'apples?', start: 41.771, end: 42.2 }] },
  { speaker: 'mila', text: 'Nine!', start: 47.26, end: 48.15, words: [{ w: 'Nine!', start: 47.34, end: 48.05 }] },
  { speaker: 'mila', text: 'Ten, take away one, is nine!', start: 49.75, end: 51.71, words: [{ w: 'Ten,', start: 49.79, end: 50.078 }, { w: 'take', start: 50.078, end: 50.438 }, { w: 'away', start: 50.438, end: 50.798 }, { w: 'one,', start: 50.798, end: 51.086 }, { w: 'is', start: 51.086, end: 51.23 }, { w: 'nine!', start: 51.23, end: 51.59 }] },
  { speaker: 'mila', text: 'Let\'s check! One, two, three, four, five, six, seven, eight, nine!', start: 53.71, end: 57.5, words: [{ w: 'Let\'s', start: 53.74, end: 54.074 }, { w: 'check!', start: 54.074, end: 54.408 }, { w: 'One,', start: 54.408, end: 54.675 }, { w: 'two,', start: 54.675, end: 54.942 }, { w: 'three,', start: 54.942, end: 55.276 }, { w: 'four,', start: 55.276, end: 55.61 }, { w: 'five,', start: 55.61, end: 55.944 }, { w: 'six,', start: 55.944, end: 56.278 }, { w: 'seven,', start: 56.278, end: 56.679 }, { w: 'eight,', start: 56.679, end: 56.946 }, { w: 'nine!', start: 56.946, end: 57.28 }] },
  { speaker: 'bobo', text: 'Yummy! Counting is fun!', start: 59.3, end: 60.6, words: [{ w: 'Yummy!', start: 59.34, end: 59.645 }, { w: 'Counting', start: 59.645, end: 60.134 }, { w: 'is', start: 60.134, end: 60.256 }, { w: 'fun!', start: 60.256, end: 60.5 }] },
];
