// AUTO-GENERATED by tools/gen_song.py — do not edit. Word times = the melody's note times.
import type { VoLine } from '../../lib/shorts';

export const SONG_BPM = 100;
export const SONG_BEAT = 0.60000;
export const SONG_DURATION = 184.40;

export const SONG: VoLine[] = [
  { speaker: "mila", text: "A, B, C, D, E, F, G!", start: 4.8, end: 9.6, words: [{ w: "A,", start: 4.8, end: 5.4 }, { w: "B,", start: 5.4, end: 6.0 }, { w: "C,", start: 6.0, end: 6.6 }, { w: "D,", start: 6.6, end: 7.2 }, { w: "E,", start: 7.2, end: 7.8 }, { w: "F,", start: 7.8, end: 8.4 }, { w: "G!", start: 8.4, end: 9.6 }] },
  { speaker: "mila", text: "H, I, J, K, L, M, N!", start: 9.6, end: 14.4, words: [{ w: "H,", start: 9.6, end: 10.2 }, { w: "I,", start: 10.2, end: 10.8 }, { w: "J,", start: 10.8, end: 11.4 }, { w: "K,", start: 11.4, end: 12.0 }, { w: "L,", start: 12.0, end: 12.6 }, { w: "M,", start: 12.6, end: 13.2 }, { w: "N!", start: 13.2, end: 14.4 }] },
  { speaker: "mila", text: "O, P, Q, R, S, T, U!", start: 14.4, end: 19.2, words: [{ w: "O,", start: 14.4, end: 15.0 }, { w: "P,", start: 15.0, end: 15.6 }, { w: "Q,", start: 15.6, end: 16.2 }, { w: "R,", start: 16.2, end: 16.8 }, { w: "S,", start: 16.8, end: 17.4 }, { w: "T,", start: 17.4, end: 18.0 }, { w: "U!", start: 18.0, end: 19.2 }] },
  { speaker: "mila", text: "V, W, X, Y, Z!", start: 19.2, end: 23.4, words: [{ w: "V,", start: 19.2, end: 19.8 }, { w: "W,", start: 19.8, end: 20.4 }, { w: "X,", start: 20.4, end: 21.6 }, { w: "Y,", start: 21.6, end: 22.2 }, { w: "Z!", start: 22.2, end: 23.4 }] },
  { speaker: "mila", text: "Sing the alphabet with me!", start: 24.0, end: 28.8, words: [{ w: "Sing", start: 24.0, end: 24.6 }, { w: "the", start: 24.6, end: 25.2 }, { w: "alphabet", start: 25.2, end: 27.0 }, { w: "with", start: 27.0, end: 27.6 }, { w: "me!", start: 27.6, end: 28.8 }] },
  { speaker: "mila", text: "A, A, apple!", start: 28.8, end: 31.2, words: [{ w: "A,", start: 28.8, end: 29.4 }, { w: "A,", start: 29.4, end: 30.0 }, { w: "apple!", start: 30.0, end: 31.2 }] },
  { speaker: "mila", text: "B, B, bear!", start: 33.6, end: 36.0, words: [{ w: "B,", start: 33.6, end: 34.4 }, { w: "B,", start: 34.4, end: 35.2 }, { w: "bear!", start: 35.2, end: 36.0 }] },
  { speaker: "mila", text: "C, C, cat!", start: 38.4, end: 40.8, words: [{ w: "C,", start: 38.4, end: 39.2 }, { w: "C,", start: 39.2, end: 40.0 }, { w: "cat!", start: 40.0, end: 40.8 }] },
  { speaker: "mila", text: "D, D, drum!", start: 43.2, end: 45.6, words: [{ w: "D,", start: 43.2, end: 44.0 }, { w: "D,", start: 44.0, end: 44.8 }, { w: "drum!", start: 44.8, end: 45.6 }] },
  { speaker: "mila", text: "E, E, egg!", start: 48.0, end: 50.4, words: [{ w: "E,", start: 48.0, end: 48.8 }, { w: "E,", start: 48.8, end: 49.6 }, { w: "egg!", start: 49.6, end: 50.4 }] },
  { speaker: "mila", text: "F, F, fox!", start: 52.8, end: 55.2, words: [{ w: "F,", start: 52.8, end: 53.6 }, { w: "F,", start: 53.6, end: 54.4 }, { w: "fox!", start: 54.4, end: 55.2 }] },
  { speaker: "mila", text: "G, G, grapes!", start: 57.6, end: 60.0, words: [{ w: "G,", start: 57.6, end: 58.4 }, { w: "G,", start: 58.4, end: 59.2 }, { w: "grapes!", start: 59.2, end: 60.0 }] },
  { speaker: "mila", text: "H, H, heart!", start: 62.4, end: 64.8, words: [{ w: "H,", start: 62.4, end: 63.2 }, { w: "H,", start: 63.2, end: 64.0 }, { w: "heart!", start: 64.0, end: 64.8 }] },
  { speaker: "mila", text: "I, I, ice cream!", start: 67.2, end: 69.6, words: [{ w: "I,", start: 67.2, end: 67.8 }, { w: "I,", start: 67.8, end: 68.4 }, { w: "ice", start: 68.4, end: 69.0 }, { w: "cream!", start: 69.0, end: 69.6 }] },
  { speaker: "mila", text: "J, J, juice!", start: 72.0, end: 74.4, words: [{ w: "J,", start: 72.0, end: 72.8 }, { w: "J,", start: 72.8, end: 73.6 }, { w: "juice!", start: 73.6, end: 74.4 }] },
  { speaker: "mila", text: "K, K, kite!", start: 76.8, end: 79.2, words: [{ w: "K,", start: 76.8, end: 77.6 }, { w: "K,", start: 77.6, end: 78.4 }, { w: "kite!", start: 78.4, end: 79.2 }] },
  { speaker: "mila", text: "L, L, lion!", start: 81.6, end: 84.0, words: [{ w: "L,", start: 81.6, end: 82.2 }, { w: "L,", start: 82.2, end: 82.8 }, { w: "lion!", start: 82.8, end: 84.0 }] },
  { speaker: "mila", text: "M, M, monkey!", start: 86.4, end: 88.8, words: [{ w: "M,", start: 86.4, end: 87.0 }, { w: "M,", start: 87.0, end: 87.6 }, { w: "monkey!", start: 87.6, end: 88.8 }] },
  { speaker: "mila", text: "N, N, nest!", start: 91.2, end: 93.6, words: [{ w: "N,", start: 91.2, end: 92.0 }, { w: "N,", start: 92.0, end: 92.8 }, { w: "nest!", start: 92.8, end: 93.6 }] },
  { speaker: "mila", text: "O, O, owl!", start: 96.0, end: 98.4, words: [{ w: "O,", start: 96.0, end: 96.8 }, { w: "O,", start: 96.8, end: 97.6 }, { w: "owl!", start: 97.6, end: 98.4 }] },
  { speaker: "mila", text: "P, P, pig!", start: 100.8, end: 103.2, words: [{ w: "P,", start: 100.8, end: 101.6 }, { w: "P,", start: 101.6, end: 102.4 }, { w: "pig!", start: 102.4, end: 103.2 }] },
  { speaker: "mila", text: "Q, Q, queen!", start: 105.6, end: 108.0, words: [{ w: "Q,", start: 105.6, end: 106.4 }, { w: "Q,", start: 106.4, end: 107.2 }, { w: "queen!", start: 107.2, end: 108.0 }] },
  { speaker: "mila", text: "R, R, rainbow!", start: 110.4, end: 112.8, words: [{ w: "R,", start: 110.4, end: 111.0 }, { w: "R,", start: 111.0, end: 111.6 }, { w: "rainbow!", start: 111.6, end: 112.8 }] },
  { speaker: "mila", text: "S, S, star!", start: 115.2, end: 117.6, words: [{ w: "S,", start: 115.2, end: 116.0 }, { w: "S,", start: 116.0, end: 116.8 }, { w: "star!", start: 116.8, end: 117.6 }] },
  { speaker: "mila", text: "T, T, tree!", start: 120.0, end: 122.4, words: [{ w: "T,", start: 120.0, end: 120.8 }, { w: "T,", start: 120.8, end: 121.6 }, { w: "tree!", start: 121.6, end: 122.4 }] },
  { speaker: "mila", text: "U, U, umbrella!", start: 124.8, end: 127.2, words: [{ w: "U,", start: 124.8, end: 125.28 }, { w: "U,", start: 125.28, end: 125.76 }, { w: "umbrella!", start: 125.76, end: 127.2 }] },
  { speaker: "mila", text: "V, V, volcano!", start: 129.6, end: 132.0, words: [{ w: "V,", start: 129.6, end: 130.08 }, { w: "V,", start: 130.08, end: 130.56 }, { w: "volcano!", start: 130.56, end: 132.0 }] },
  { speaker: "mila", text: "W, W, watermelon!", start: 134.4, end: 136.8, words: [{ w: "W,", start: 134.4, end: 134.8 }, { w: "W,", start: 134.8, end: 135.2 }, { w: "watermelon!", start: 135.2, end: 136.8 }] },
  { speaker: "mila", text: "X, X, xylophone!", start: 139.2, end: 141.6, words: [{ w: "X,", start: 139.2, end: 139.68 }, { w: "X,", start: 139.68, end: 140.16 }, { w: "xylophone!", start: 140.16, end: 141.6 }] },
  { speaker: "mila", text: "Y, Y, yoyo!", start: 144.0, end: 146.4, words: [{ w: "Y,", start: 144.0, end: 144.6 }, { w: "Y,", start: 144.6, end: 145.2 }, { w: "yoyo!", start: 145.2, end: 146.4 }] },
  { speaker: "mila", text: "Z, Z, zigzag!", start: 148.8, end: 151.2, words: [{ w: "Z,", start: 148.8, end: 149.4 }, { w: "Z,", start: 149.4, end: 150.0 }, { w: "zigzag!", start: 150.0, end: 151.2 }] },
  { speaker: "mila", text: "A, B, C, D, E, F, G!", start: 153.6, end: 158.4, words: [{ w: "A,", start: 153.6, end: 154.2 }, { w: "B,", start: 154.2, end: 154.8 }, { w: "C,", start: 154.8, end: 155.4 }, { w: "D,", start: 155.4, end: 156.0 }, { w: "E,", start: 156.0, end: 156.6 }, { w: "F,", start: 156.6, end: 157.2 }, { w: "G!", start: 157.2, end: 158.4 }] },
  { speaker: "mila", text: "H, I, J, K, L, M, N!", start: 158.4, end: 163.2, words: [{ w: "H,", start: 158.4, end: 159.0 }, { w: "I,", start: 159.0, end: 159.6 }, { w: "J,", start: 159.6, end: 160.2 }, { w: "K,", start: 160.2, end: 160.8 }, { w: "L,", start: 160.8, end: 161.4 }, { w: "M,", start: 161.4, end: 162.0 }, { w: "N!", start: 162.0, end: 163.2 }] },
  { speaker: "mila", text: "O, P, Q, R, S, T, U!", start: 163.2, end: 168.0, words: [{ w: "O,", start: 163.2, end: 163.8 }, { w: "P,", start: 163.8, end: 164.4 }, { w: "Q,", start: 164.4, end: 165.0 }, { w: "R,", start: 165.0, end: 165.6 }, { w: "S,", start: 165.6, end: 166.2 }, { w: "T,", start: 166.2, end: 166.8 }, { w: "U!", start: 166.8, end: 168.0 }] },
  { speaker: "mila", text: "V, W, X, Y, Z!", start: 168.0, end: 172.2, words: [{ w: "V,", start: 168.0, end: 168.6 }, { w: "W,", start: 168.6, end: 169.2 }, { w: "X,", start: 169.2, end: 170.4 }, { w: "Y,", start: 170.4, end: 171.0 }, { w: "Z!", start: 171.0, end: 172.2 }] },
  { speaker: "mila", text: "Sing the alphabet with me!", start: 172.8, end: 177.6, words: [{ w: "Sing", start: 172.8, end: 173.4 }, { w: "the", start: 173.4, end: 174.0 }, { w: "alphabet", start: 174.0, end: 175.8 }, { w: "with", start: 175.8, end: 176.4 }, { w: "me!", start: 176.4, end: 177.6 }] },
];
