// AUTO-GENERATED by the Day 17 pack script — line indices into VO.
export const PLAN = {
 "colors": [
  {
   "en": "One",
   "fr": "un",
   "hex": "#ff595e",
   "obj": "apple",
   "en1": 2,
   "en2": 3,
   "fr1": 4,
   "fr2": 5,
   "say": 6
  },
  {
   "en": "Two",
   "fr": "deux",
   "hex": "#ff924c",
   "obj": "balloon",
   "en1": 7,
   "en2": 8,
   "fr1": 9,
   "fr2": 10,
   "say": 11
  },
  {
   "en": "Three",
   "fr": "trois",
   "hex": "#ffca3a",
   "obj": "star",
   "en1": 12,
   "en2": 13,
   "fr1": 14,
   "fr2": 15,
   "say": 16
  },
  {
   "en": "Four",
   "fr": "quatre",
   "hex": "#8ac926",
   "obj": "apple",
   "en1": 17,
   "en2": 18,
   "fr1": 19,
   "fr2": 20,
   "say": 21
  },
  {
   "en": "Five",
   "fr": "cinq",
   "hex": "#1982c4",
   "obj": "balloon",
   "en1": 22,
   "en2": 23,
   "fr1": 24,
   "fr2": 25,
   "say": 26
  },
  {
   "en": "Six",
   "fr": "six",
   "hex": "#6a4c93",
   "obj": "star",
   "en1": 30,
   "en2": 31,
   "fr1": 32,
   "fr2": 33,
   "say": 34
  },
  {
   "en": "Seven",
   "fr": "sept",
   "hex": "#ff6fa5",
   "obj": "apple",
   "en1": 35,
   "en2": 36,
   "fr1": 37,
   "fr2": 38,
   "say": 39
  },
  {
   "en": "Eight",
   "fr": "huit",
   "hex": "#4cc9f0",
   "obj": "balloon",
   "en1": 40,
   "en2": 41,
   "fr1": 42,
   "fr2": 43,
   "say": 44
  },
  {
   "en": "Nine",
   "fr": "neuf",
   "hex": "#52b788",
   "obj": "star",
   "en1": 45,
   "en2": 46,
   "fr1": 47,
   "fr2": 48,
   "say": 49
  },
  {
   "en": "Ten",
   "fr": "dix",
   "hex": "#f15bb5",
   "obj": "apple",
   "en1": 50,
   "en2": 51,
   "fr1": 52,
   "fr2": 53,
   "say": 54
  },
  {
   "en": "Eleven",
   "fr": "onze",
   "hex": "#ff595e",
   "obj": "balloon",
   "en1": 58,
   "en2": 59,
   "fr1": 60,
   "fr2": 61,
   "say": 62
  },
  {
   "en": "Twelve",
   "fr": "douze",
   "hex": "#ff924c",
   "obj": "star",
   "en1": 63,
   "en2": 64,
   "fr1": 65,
   "fr2": 66,
   "say": 67
  },
  {
   "en": "Thirteen",
   "fr": "treize",
   "hex": "#ffca3a",
   "obj": "apple",
   "en1": 68,
   "en2": 69,
   "fr1": 70,
   "fr2": 71,
   "say": 72
  },
  {
   "en": "Fourteen",
   "fr": "quatorze",
   "hex": "#8ac926",
   "obj": "balloon",
   "en1": 73,
   "en2": 74,
   "fr1": 75,
   "fr2": 76,
   "say": 77
  },
  {
   "en": "Fifteen",
   "fr": "quinze",
   "hex": "#1982c4",
   "obj": "star",
   "en1": 78,
   "en2": 79,
   "fr1": 80,
   "fr2": 81,
   "say": 82
  },
  {
   "en": "Sixteen",
   "fr": "seize",
   "hex": "#6a4c93",
   "obj": "apple",
   "en1": 86,
   "en2": 87,
   "fr1": 88,
   "fr2": 89,
   "say": 90
  },
  {
   "en": "Seventeen",
   "fr": "dix-sept",
   "hex": "#ff6fa5",
   "obj": "balloon",
   "en1": 91,
   "en2": 92,
   "fr1": 93,
   "fr2": 94,
   "say": 95
  },
  {
   "en": "Eighteen",
   "fr": "dix-huit",
   "hex": "#4cc9f0",
   "obj": "star",
   "en1": 96,
   "en2": 97,
   "fr1": 98,
   "fr2": 99,
   "say": 100
  },
  {
   "en": "Nineteen",
   "fr": "dix-neuf",
   "hex": "#52b788",
   "obj": "apple",
   "en1": 101,
   "en2": 102,
   "fr1": 103,
   "fr2": 104,
   "say": 105
  },
  {
   "en": "Twenty",
   "fr": "vingt",
   "hex": "#f15bb5",
   "obj": "balloon",
   "en1": 106,
   "en2": 107,
   "fr1": 108,
   "fr2": 109,
   "say": 110
  }
 ],
 "quiz": [
  {
   "target": 2,
   "options": [
    1,
    2,
    4
   ],
   "correct": 1,
   "ask": 27,
   "ans": 28,
   "ansFr": 29
  },
  {
   "target": 6,
   "options": [
    6,
    7,
    9
   ],
   "correct": 0,
   "ask": 55,
   "ans": 56,
   "ansFr": 57
  },
  {
   "target": 11,
   "options": [
    11,
    12,
    13
   ],
   "correct": 0,
   "ask": 83,
   "ans": 84,
   "ansFr": 85
  },
  {
   "target": 16,
   "options": [
    15,
    16,
    18
   ],
   "correct": 1,
   "ask": 111,
   "ans": 112,
   "ansFr": 113
  }
 ],
 "recapEn": [
  115,
  116,
  117,
  118
 ],
 "recapFr": [
  120,
  121,
  122,
  123
 ],
 "bye": 124,
 "byeBobo": 125
} as const;
