// AUTO-GENERATED by the Day 5 pack script — VO line index by key.
export const K = {
 "why": 0,
 "guess": 1,
 "good": 2,
 "white": 3,
 "rainbow": 4,
 "air": 5,
 "bounce": 6,
 "eyes": 7,
 "word": 8,
 "mila_say": 9,
 "leo_say": 10,
 "recap": 11,
 "r1": 12,
 "r2": 13,
 "r3": 14,
 "leo_wow": 15,
 "wow": 16,
 "end": 17
} as const;
