// AUTO-GENERATED by the Day 3 pack script — line indices into VO.
export const PLAN = {
 "animals": [
  {
   "species": "lion",
   "en": "Lion",
   "fr": "le lion",
   "enLine": 2,
   "frLine": 3,
   "sayLine": 4
  },
  {
   "species": "pig",
   "en": "Pig",
   "fr": "le cochon",
   "enLine": 5,
   "frLine": 6,
   "sayLine": 7
  },
  {
   "species": "cat",
   "en": "Cat",
   "fr": "le chat",
   "enLine": 8,
   "frLine": 9,
   "sayLine": 10
  },
  {
   "species": "fox",
   "en": "Fox",
   "fr": "le renard",
   "enLine": 13,
   "frLine": 14,
   "sayLine": 15
  },
  {
   "species": "bunny",
   "en": "Rabbit",
   "fr": "le lapin",
   "enLine": 16,
   "frLine": 17,
   "sayLine": 18
  },
  {
   "species": "mouse",
   "en": "Mouse",
   "fr": "la souris",
   "enLine": 19,
   "frLine": 20,
   "sayLine": 21
  },
  {
   "species": "panda",
   "en": "Panda",
   "fr": "le panda",
   "enLine": 24,
   "frLine": 25,
   "sayLine": 26
  },
  {
   "species": "owl",
   "en": "Owl",
   "fr": "le hibou",
   "enLine": 27,
   "frLine": 28,
   "sayLine": 29
  },
  {
   "species": "frog",
   "en": "Frog",
   "fr": "la grenouille",
   "enLine": 30,
   "frLine": 31,
   "sayLine": 32
  },
  {
   "species": "bear",
   "en": "Bear",
   "fr": "l'ours",
   "enLine": 35,
   "frLine": 36,
   "sayLine": 37
  }
 ],
 "quiz": [
  {
   "word": "cat",
   "options": [
    "lion",
    "cat",
    "pig"
   ],
   "correct": 1,
   "ask": 11,
   "ans": 12
  },
  {
   "word": "rabbit",
   "options": [
    "fox",
    "bunny",
    "mouse"
   ],
   "correct": 1,
   "ask": 22,
   "ans": 23
  },
  {
   "word": "frog",
   "options": [
    "panda",
    "owl",
    "frog"
   ],
   "correct": 2,
   "ask": 33,
   "ans": 34
  }
 ],
 "recapEn": 38,
 "recapFr": 39,
 "bye": 40,
 "byeBobo": 41
} as const;
