import React from 'react';
import { AbsoluteFill, Sequence, useCurrentFrame } from 'remotion';
import { BigTitle, Captions, PauseCard, ProgressBar, ShortsBackdrop, prog } from '../../lib/shorts';
import {
  BigCount,
  DayRail,
  Disclaimer,
  EASE_INOUT,
  EASE_OUT,
  EdgeLine,
  FactPlate,
  FormulaChip,
  Hull,
  NP,
  NodeDisc,
  Pair,
  Person,
  Pt,
  Stat,
  TurnDot,
  clamp01,
  hullOf,
  mix,
  nChoose2,
  pairsOf,
  relax,
  ringAnchors,
} from '../../lib/pairs';
import { VO } from './vo.gen';

// =============================================================================
// COMPOSITION CONFIG
// =============================================================================
export const compositionConfig = {
  id: 'Short27Pairs',
  durationInSeconds: 45.0,
  fps: 30,
  width: 1080,
  height: 1920,
};

const F = (s: number) => Math.round(s * 30);
const END = F(45.0); // 1350

// =============================================================================
// THE MODEL — the roster, and nothing else authored.
//
// These five people are the ONLY content in the video. The relationships are GENERATED by
// pairsOf(): four people make six, five make ten, and every number on screen — the count, the
// people, the minutes, the days on the rail, the formula chip — is read off the nodes and
// edges actually drawn on the current frame. Nothing is typed twice, so the twist cannot
// disagree with the hook: add GRAN to the roster and the whole video re-argues itself.
//
// The household is an ILLUSTRATION and the disclaimer says so. The one SOURCED claim is the
// plate in the band (see beats.json.facts): the daily one-on-one dose that has actually been
// randomised is five minutes, in a dyad.
// =============================================================================
const HOUSE: Person[] = [
  { id: 'mum', name: 'Mum', sub: 'parent', color: '#c9d1d9' },
  { id: 'dad', name: 'Dad', sub: 'parent', color: '#c9d1d9' },
  { id: 'ana', name: 'Ana', sub: 'age 9', color: '#c9d1d9' },
  { id: 'leo', name: 'Leo', sub: 'age 6', color: '#c9d1d9' },
  { id: 'gran', name: 'Gran', sub: 'moved in', color: NP.violet }, // the twist, on the roster
];

const N4 = 4;
const N5 = HOUSE.length; // 5
const PAIRS4: Pair[] = pairsOf(N4); //  6 — the household the video opens on
const PAIRS5: Pair[] = pairsOf(N5); // 10 — the household it ends up describing
const NEW_PAIRS: Pair[] = PAIRS5.filter((p) => p.b >= N4); // the four GRAN brings with her
const KEY4 = new Set(PAIRS4.map((p) => p.key));
const IDX4 = new Map(PAIRS4.map((p, i) => [p.key, i])); // sweep order — the original six only

// The two edges the video calls out: the COUPLE and the SIBLINGS — the pairs a household
// never schedules, because no logistics force them to be alone together.
const K_COUPLE = '0-1';
const K_SIBS = '2-3';
// The four parent-child pairs, in the order the rotation feeds them.
const K_ROTA = ['1-3', '0-2', '0-3', '1-2'];

// =============================================================================
// LAYOUT — nothing critical below y1390 or outside x[60,920]. The extremes were measured
// against the relaxation, not guessed: the widest the house ever gets is the starved setup
// (discs x210..868, labels down to y1082) and the big count's glyphs start at y1101.
// =============================================================================
const CX = 540;
const CY = 680;
const R0 = 235;
const NODE_R = 56;
const HULL_PAD = 100;
const CHIP_Y = 300;
const STAT_Y = 1170;
const BIG_Y = 1190;
const RAIL_Y = 1290;
const RAIL_W = 700;
const DISC_Y = 1386;
const BAND_Y = 96;

const ANCH4 = ringAnchors(N4, CX, CY, R0);
const ANCH5 = ringAnchors(N5, CX, CY, R0);

// =============================================================================
// CUES — GLOBAL frames. Every one is a REAL word time out of beats.json; the comment is the
// word it lands on. Inside a <Sequence> the frame is LOCAL, so Board is handed its sequence's
// `from` and adds it back before comparing against anything below.
// =============================================================================
const HOOK_OUT = F(4.2); // 126
const SETUP_OUT = F(10.85); // 326
const QUIZ_OUT = F(13.65); // 410  (84 frames = the card's 2.80s)
const REVEAL_OUT = F(34.95); // 1049
const TWIST_OUT = F(41.1); // 1233

const SWEEP1_A = 18; //  0.60  the six edges light in turn under the hook line, so the 6 in
const SWEEP1_STEP = 11; //       the readout is visibly a COUNT of things on screen
const SWEEP2_A = 452; // 15.07  and again under "you count pairs"
const SWEEP2_STEP = 9;

const DRAIN_A = 118; //  3.93  the finished week rewinds — this is what earns the loop
const DRAIN_B = 148; //  4.93

const HULL_A = 146; //  4.87  lands under "together" (4.93), 10 frames after the chip is gone
const HULL_B = 172; //  5.73
const HULL_C = 312; // 10.40  clears before the card settles
const HULL_D = 334; // 11.13
const ALONE_POP = 266; //  8.86  "alone" — the minutes readout is sitting on zero

const DIM_A = 320; // 10.67  the house steps back for the card
const DIM_B = 340; // 11.33
const UNDIM_A = 404; // 13.47
const UNDIM_B = 424; // 14.13

// The card asks how many relationships are in YOUR house, so the readouts that answer it for
// THIS house go down with the question and come back with the reveal (short-26's rule: never
// print the answer above the card). The formula chip leaves earlier still — it also has to
// clear the strip the evening hull's label uses.
const ANS_OUT_A = 300; // 10.00
const ANS_OUT_B = 328; // 10.93
const ANS_IN_A = 412; // 13.73
const ANS_IN_B = 442; // 14.73
const CHIP_OUT_A = 112; //  3.73  leaves with the rewind, and clears the strip the hull's
const CHIP_OUT_B = 136; //  4.53  own label is about to use
const CHIP_IN_A = 452; // 15.07  "you count pairs" (15.15)
const CHIP_IN_B = 478; // 15.93

const PEOPLE_POP = 433; // 14.44  "people,"
const COUNT_POP = 465; // 15.51  "pairs."

/** A TURN: ten minutes spent on one pair. The dot travels the edge and the edge fills. */
const TURNS: { key: string; a: number; b: number }[] = [
  { key: '1-3', a: 510, b: 546 }, // 16.99  "Ten minutes, one person, no phone, no plan."
  { key: '0-2', a: 630, b: 658 }, // 21.00  "One pair a day..."
  { key: '0-3', a: 660, b: 688 },
  { key: '1-2', a: 690, b: 718 }, // ...ends under "takes six." (22.81)
  { key: '0-1', a: 824, b: 856 }, // 27.47  "One hour a week..." — the couple
  { key: '2-3', a: 858, b: 890 }, // ...and the siblings, landing under "turn." (29.70)
];
const TURN_OF = new Map(TURNS.map((t) => [t.key, t]));

const RING1_A = 727; // 24.23  "couple"  — ringed while it is still dark
const RING1_B = 745;
const RING2_A = 750; // 25.00  "siblings"
const RING2_B = 768;
const MIN_POP = 891; // 29.70  "turn." — sixty minutes, and every relationship has had one

const PLATE_A = 925; // 30.83  "Ten is generous. The tested version is five." (30.94)
const PLATE_B = 947;
const PLATE_C = 1026; // 34.20
const PLATE_D = 1046;

const GRAN_A = 1068; // 35.60  "moves in," (35.56) — the fifth person arrives
const GRAN_B = 1110;
const NEW_IN = [1096, 1104, 1112, 1120]; // 36.53..37.33  the four lines she brings, one at a
const NEW_DUR = 16; //                      time, so the count ticks 6-7-8-9-10 under "four
const TEN_POP = 1184; // 39.47  "Ten now, not six."   relationships,"
const GRAN_OUT_A = 1245; // 41.50  she leaves the drawing with the loop, not with the argument
const GRAN_OUT_B = 1292; // 43.07

const TITLE_OUT_A = 280; //  9.33  clears the band before the pause card
const TITLE_OUT_B = 316; // 10.53
const TITLE_IN_A = 1250; // 41.67  "So it can't be a mood." (41.49)
const TITLE_IN_B = 1306; // 43.53

// =============================================================================
// STATE AS A FUNCTION OF THE GLOBAL FRAME.
// Every one of these returns its frame-0 value at f = END-1 by construction — each is a
// product of ramps that is 1 (or 0) at both ends. The loop is authored, not debugged in.
// =============================================================================

/** in -> hold -> out. */
const band = (f: number, a: number, b: number, c: number, d: number) =>
  EASE_OUT(prog(f, a, b)) * (1 - EASE_INOUT(prog(f, c, d)));

/** A short pop on a readout the narration has just named. */
const pop = (f: number, at: number) => band(f, at, at + 7, at + 26, at + 44);

/** How much one-on-one time this pair has had. 1 at f=0 (the finished week), rewound to 0 by
 *  the setup, and rebuilt to 1 by its own turn — so f=END-1 is f=0 again, edge for edge. */
const chargeAt = (key: string, f: number): number => {
  const rewound = 1 - EASE_INOUT(prog(f, DRAIN_A, DRAIN_B));
  const t = TURN_OF.get(key);
  const turn = t ? EASE_OUT(prog(f, t.a, t.b)) : 0;
  return Math.max(rewound, turn);
};

/** GRAN's presence, and the presence of each line she brings with her. */
const granAt = (f: number) =>
  EASE_OUT(prog(f, GRAN_A, GRAN_B)) * (1 - EASE_INOUT(prog(f, GRAN_OUT_A, GRAN_OUT_B)));

const newEdgeAt = (j: number, f: number) =>
  EASE_OUT(prog(f, NEW_IN[j], NEW_IN[j] + NEW_DUR)) * (1 - EASE_INOUT(prog(f, GRAN_OUT_A, GRAN_OUT_B)));

const presenceAt = (key: string, f: number): number => {
  if (KEY4.has(key)) return 1;
  const j = NEW_PAIRS.findIndex((p) => p.key === key);
  return j < 0 ? 0 : newEdgeAt(j, f);
};

const hullAt = (f: number) => band(f, HULL_A, HULL_B, HULL_C, HULL_D);
const dimAt = (f: number) =>
  1 - 0.28 * EASE_INOUT(prog(f, DIM_A, DIM_B)) * (1 - EASE_INOUT(prog(f, UNDIM_A, UNDIM_B)));

/** 1 at f=0 and at f=END-1; 0 only while the card is asking. */
const answerOpAt = (f: number) =>
  Math.min(1, 1 - EASE_INOUT(prog(f, ANS_OUT_A, ANS_OUT_B)) + EASE_OUT(prog(f, ANS_IN_A, ANS_IN_B)));

const chipOpAt = (f: number) =>
  Math.min(1, 1 - EASE_INOUT(prog(f, CHIP_OUT_A, CHIP_OUT_B)) + EASE_OUT(prog(f, CHIP_IN_A, CHIP_IN_B)));

const ringOf = (key: string, f: number): number => {
  if (key === K_COUPLE) return band(f, RING1_A, RING1_B, TURNS[4].a - 4, TURNS[4].a + 16);
  if (key === K_SIBS) return band(f, RING2_A, RING2_B, TURNS[5].a - 4, TURNS[5].a + 16);
  return 0;
};

/** The six edges flare in turn, twice, so the readout is seen to be counting them. */
const flareAt = (i: number, f: number) =>
  Math.max(
    band(f, SWEEP1_A + i * SWEEP1_STEP, SWEEP1_A + i * SWEEP1_STEP + 7, SWEEP1_A + i * SWEEP1_STEP + 14, SWEEP1_A + i * SWEEP1_STEP + 24),
    band(f, SWEEP2_A + i * SWEEP2_STEP, SWEEP2_A + i * SWEEP2_STEP + 6, SWEEP2_A + i * SWEEP2_STEP + 12, SWEEP2_A + i * SWEEP2_STEP + 20),
  );

const titleOpAt = (f: number) =>
  Math.min(1, 1 - EASE_INOUT(prog(f, TITLE_OUT_A, TITLE_OUT_B)) + EASE_OUT(prog(f, TITLE_IN_A, TITLE_IN_B)));

/** The whole board breathes 10px between the hook and the wrap, and lands back where it began. */
const driftAt = (f: number) =>
  f < 600 ? mix(-10, 0, EASE_OUT(prog(f, 0, 110))) : mix(0, -10, EASE_INOUT(prog(f, TITLE_IN_A, END - 1)));

// =============================================================================
// THE BOARD — the one persistent thing the whole video happens on. The beats only switch
// pieces of it on; nothing ever cuts.
// =============================================================================
const Board: React.FC<{ from: number }> = ({ from }) => {
  const f = useCurrentFrame() + from; // GLOBAL frame

  // ---- the household on THIS frame -------------------------------------------------------
  const gran = granAt(f);
  const charge = (k: string) => chargeAt(k, f);
  const weight = (k: string) => presenceAt(k, f);

  // The ring opens up to make room for a fifth person as she arrives, so nobody teleports.
  const anchors: Pt[] = ANCH5.map((a5, i) => (i < N4 ? { x: mix(ANCH4[i].x, a5.x, gran), y: mix(ANCH4[i].y, a5.y, gran) } : a5));
  const P = relax(anchors, PAIRS5, charge, { near: 330, far: 470, weightOf: weight });

  // ---- every number below is a COUNT of what is drawn above, never a constant -------------
  const nodesDrawn = N4 + (gran >= 0.5 ? 1 : 0);
  const edgesDrawn = PAIRS5.filter((p) => presenceAt(p.key, f) >= 0.5).length;
  const fedPairs = PAIRS5.filter((p) => presenceAt(p.key, f) >= 0.5 && charge(p.key) >= 0.5).length;
  const railFill = PAIRS5.reduce((s, p) => s + presenceAt(p.key, f) * clamp01(charge(p.key)), 0);
  const minutes = fedPairs * 10;

  const dim = dimAt(f);
  const ans = answerOpAt(f);
  const hull = hullAt(f);
  const hullPts = hullOf(P.slice(0, nodesDrawn), HULL_PAD);

  return (
    <div style={{ position: 'absolute', inset: 0, transform: `translateY(${driftAt(f)}px)` }}>
      <svg width={1080} height={1920} viewBox="0 0 1080 1920" style={{ position: 'absolute', left: 0, top: 0 }}>
        <g opacity={dim}>
          {/* everyone in the room at once — ONE shape, because inside it nobody is alone
              with anybody. It never touches an edge; an edge is one-on-one minutes. */}
          <Hull pts={hullPts} opacity={hull} label="MONDAY EVENING · 90 MIN TOGETHER" />

          {PAIRS5.map((p) => {
            const pres = presenceAt(p.key, f);
            if (pres <= 0.01) return null;
            const c = clamp01(charge(p.key));
            const flare = KEY4.has(p.key) ? flareAt(IDX4.get(p.key) ?? 0, f) : 0;
            const t = TURN_OF.get(p.key);
            return (
              <g key={p.key}>
                <EdgeLine
                  A={P[p.a]}
                  B={P[p.b]}
                  charge={Math.max(c, 0.34 * flare)}
                  opacity={pres}
                  ring={ringOf(p.key, f)}
                  label="10 MIN"
                  labelOpacity={t === TURNS[0] ? band(f, t.a + 6, t.a + 16, t.b + 30, t.b + 54) : 0}
                />
                {t ? (
                  <TurnDot
                    A={P[p.a]}
                    B={P[p.b]}
                    t={prog(f, t.a, t.b)}
                    opacity={band(f, t.a - 5, t.a + 4, t.b - 8, t.b)}
                  />
                ) : null}
              </g>
            );
          })}

          {HOUSE.map((person, i) => (
            <NodeDisc key={person.id} p={P[i]} person={person} r={NODE_R} opacity={i < N4 ? 1 : gran} />
          ))}
        </g>

        {/* ---- THE READOUTS. Six numbers, none of them a constant: the people drawn, the
             edges drawn, the pairs that have had their ten minutes, and n(n-1)/2 printed
             with the roster's own n. A mis-timed animation shows a WRONG number here
             instead of hiding behind a keyframed counter. --------------------------------- */}
        <FormulaChip n={nodesDrawn} cx={CX} y={CHIP_Y} opacity={chipOpAt(f)} />
        <g opacity={ans}>
          <Stat value={`${nodesDrawn}`} label="PEOPLE" x={230} y={STAT_Y} opacity={0.92} />
          <BigCount
            n={edgesDrawn}
            label="RELATIONSHIPS"
            x={CX}
            y={BIG_Y}
            color={NP.fed}
            pulse={Math.max(pop(f, COUNT_POP), pop(f, TEN_POP))}
          />
          <Stat
            value={`${minutes}`}
            label="MIN / WEEK"
            x={830}
            y={STAT_Y}
            color={minutes > 0 ? NP.fed : NP.text}
            opacity={0.92}
          />
          <g transform={`translate(${CX} ${RAIL_Y}) scale(${1 + 0.04 * Math.max(pop(f, ALONE_POP), pop(f, MIN_POP))}) translate(${-CX} ${-RAIL_Y})`}>
            <DayRail slots={edgesDrawn} filled={railFill} cx={CX} y={RAIL_Y} w={RAIL_W} />
          </g>
          <g opacity={pop(f, PEOPLE_POP) * 0.9}>
            <circle cx={230} cy={STAT_Y - 20} r={62} fill="none" stroke={NP.warn} strokeWidth={3} />
          </g>
        </g>
      </svg>
    </div>
  );
};

// =============================================================================
// THE BAND — the title, and the one sourced finding that borrows its strip. Nothing here
// ever covers the household it is talking about.
// =============================================================================
const BandLayer: React.FC = () => {
  const f = useCurrentFrame(); // GLOBAL — this layer is never inside a Sequence
  const plate = band(f, PLATE_A, PLATE_B, PLATE_C, PLATE_D);
  return (
    <>
      <div style={{ position: 'absolute', inset: 0, opacity: titleOpAt(f) }}>
        <BigTitle
          warm
          y={104}
          size={58}
          lines={[{ text: 'YOUR FAMILY IS NOT FOUR PEOPLE' }, { text: 'IT IS SIX RELATIONSHIPS', color: NP.fed }]}
        />
      </div>

      {plate > 0.01 ? (
        <FactPlate
          y={BAND_Y}
          opacity={plate}
          headline="THE TESTED DOSE IS 5 MIN A DAY, ONE ADULT ONE CHILD"
          source={[
            'PCIT CHILD-DIRECTED INTERACTION · DAILY 5-MIN HOME PRACTICE',
            'WARD, THEULE & CHEUNG 2016 META-ANALYSIS · d = -1.65 · 12 RCTs, 372 CHILDREN',
            'CLINIC-REFERRED 2-5s WITH CONDUCT PROBLEMS, NOT TYPICAL HOUSEHOLDS',
          ]}
        />
      ) : null}
    </>
  );
};

// =============================================================================
// THE SHOT
// =============================================================================
export default function Short27Pairs() {
  return (
    <AbsoluteFill style={{ background: NP.stage }}>
      <ShortsBackdrop />

      {/* HOOK — frame 0 fully composed: the finished week, six lit edges pulled tight, the
          count, the formula and sixty minutes already on screen. The six flare in turn so
          the number is seen to be a count. */}
      <Sequence from={0} durationInFrames={HOOK_OUT}>
        <Board from={0} />
      </Sequence>

      {/* SETUP — the week rewinds to empty and the house spreads apart, then the evening
          arrives as ONE shape over all four of them. Six relationships, zero minutes. */}
      <Sequence from={HOOK_OUT} durationInFrames={SETUP_OUT - HOOK_OUT}>
        <Board from={HOOK_OUT} />
      </Sequence>

      {/* QUIZ — the card sits over the dimmed house. The question is about THEIR house, and
          the formula that answers it does not arrive until the reveal. */}
      <Sequence from={SETUP_OUT} durationInFrames={QUIZ_OUT - SETUP_OUT}>
        <Board from={SETUP_OUT} />
        {/* The card sits on the READOUTS, not on the household: the four people stay fully
            drawn so the viewer can count their own, and the numbers that answer it are gone. */}
        <PauseCard
          title="PAUSE"
          subtitle="how many are in your house?"
          durSec={(QUIZ_OUT - SETUP_OUT) / 30}
          y={1180}
          accent={NP.fed}
        />
      </Sequence>

      {/* REVEAL — the formula, then one ten-minute turn, then the rotation. The four
          parent-child pairs go first; the couple and the siblings are ringed while they are
          still dark, and only then get their turn. Sixty minutes, six relationships. */}
      <Sequence from={QUIZ_OUT} durationInFrames={REVEAL_OUT - QUIZ_OUT}>
        <Board from={QUIZ_OUT} />
      </Sequence>

      {/* TWIST — a fifth person arrives and brings four lines with her, one at a time, so the
          count ticks 6-7-8-9-10 while the narration says "four". The rail grows with it. */}
      <Sequence from={REVEAL_OUT} durationInFrames={TWIST_OUT - REVEAL_OUT}>
        <Board from={REVEAL_OUT} />
      </Sequence>

      {/* LOOP — she leaves the drawing, the six settle back tight, the title returns. The
          last frame is the first frame, edge for edge. No CTA. */}
      <Sequence from={TWIST_OUT} durationInFrames={END - TWIST_OUT}>
        <Board from={TWIST_OUT} />
      </Sequence>

      {/* GLOBAL */}
      <BandLayer />
      <Disclaimer y={DISC_Y} text="THE HOUSEHOLD IS AN ILLUSTRATION · THE PAIR COUNT IS n(n-1)/2" />
      <Captions lines={VO} y={1462} size={52} accent={NP.fed} plate />
      <ProgressBar color={NP.fed} />
    </AbsoluteFill>
  );
}

// The video's whole claim, asserted against the drawing rather than typed into it: the edges
// generated are the formula printed, and the rotation feeds every one of them exactly once —
// the four parent-child pairs, then the two nobody schedules.
if (PAIRS4.length !== nChoose2(N4) || PAIRS5.length !== nChoose2(N5)) {
  throw new Error('pairsOf disagrees with n(n-1)/2');
}
const ROTATION = [...K_ROTA, K_COUPLE, K_SIBS];
if (ROTATION.length !== PAIRS4.length || new Set(ROTATION).size !== PAIRS4.length || ROTATION.some((k) => !KEY4.has(k))) {
  throw new Error('the rotation does not cover the six relationships exactly once');
}
if (TURNS.length !== PAIRS4.length || TURNS.some((t, i) => t.key !== ROTATION[i])) {
  throw new Error('the turns on the timeline are not the rotation');
}
