// AUTO-GENERATED by the Day 24 pack script — line indices into VO.
export const PLAN = {
 "colors": [
  {
   "en": "Mom",
   "fr": "maman",
   "hex": "#ff6fa5",
   "obj": "mom",
   "en1": 2,
   "en2": 3,
   "fr1": 4,
   "fr2": 5,
   "say": 6
  },
  {
   "en": "Dad",
   "fr": "papa",
   "hex": "#1982c4",
   "obj": "dad",
   "en1": 7,
   "en2": 8,
   "fr1": 9,
   "fr2": 10,
   "say": 11
  },
  {
   "en": "Sister",
   "fr": "la soeur",
   "hex": "#ffca3a",
   "obj": "sister",
   "en1": 12,
   "en2": 13,
   "fr1": 14,
   "fr2": 15,
   "say": 16
  },
  {
   "en": "Brother",
   "fr": "le frère",
   "hex": "#8ac926",
   "obj": "brother",
   "en1": 17,
   "en2": 18,
   "fr1": 19,
   "fr2": 20,
   "say": 21
  },
  {
   "en": "Grandma",
   "fr": "mamie",
   "hex": "#b8a1e3",
   "obj": "grandma",
   "en1": 22,
   "en2": 23,
   "fr1": 24,
   "fr2": 25,
   "say": 26
  },
  {
   "en": "Grandpa",
   "fr": "papi",
   "hex": "#ff924c",
   "obj": "grandpa",
   "en1": 27,
   "en2": 28,
   "fr1": 29,
   "fr2": 30,
   "say": 31
  }
 ],
 "quiz": [],
 "recapEn": [
  33,
  34
 ],
 "recapFr": [
  36,
  37
 ],
 "bye": 38,
 "byeBobo": 39
} as const;
