import React from 'react';
import { AbsoluteFill, Easing, Sequence, useCurrentFrame } from 'remotion';
import {
  BigTitle,
  Captions,
  Kicker,
  PauseCard,
  ProgressBar,
  ShortsBackdrop,
  Stamp,
  StatChip,
  prog,
} from '../../lib/shorts';
import { Arrow, BoardMove, ChessBoard, Highlight, START_FEN, Sq, fenBoard, sqCenter } from '../../lib/chess';
import { FONT_MONO } from '../../fonts';
import { VO } from './vo.gen';

// =============================================================================
// COMPOSITION CONFIG
// =============================================================================
export const compositionConfig = {
  id: 'Short1Chess',
  durationInSeconds: 42,
  fps: 30,
  width: 1080,
  height: 1920,
};

// =============================================================================
// STYLE CONSTANTS
// =============================================================================
const GOLD = '#f5d76e';
const RED = '#e8879f';
const GREEN = '#4db8a8';
const GRAY = '#8b949e';
const EASE_INOUT = Easing.bezier(0.37, 0, 0.63, 1);

// Board geometry (shared by hook / main / loop so the loop lands on the hook frame)
const B = { size: 940, x: 70, y: 470 } as const;
const PAD = Math.round((B.size / 8) * 0.16);
const SQ = B.size / 8;

// =============================================================================
// DATA — mirrors shorts/short-1-chess/beats.json (timings in GLOBAL seconds; the
// main scene mounts at 3.2s, so local frame = global*30 - 96)
// =============================================================================
// VO (text + exact word times) lives in ./vo.gen.ts — regenerated by tools/gen_voice.py.

const MATE_FEN = 'r1bqkb1r/pppp1Qpp/2n2n2/4p3/2B1P3/8/PPPP1PPP/RNB1K1NR';

// Main-scene move timeline (local frames; scene starts at global frame 96)
const MOVES: BoardMove[] = [
  { from: 'e2', to: 'e4', at: 39, dur: 12 },
  { from: 'e7', to: 'e5', at: 66, dur: 12 },
  { from: 'f1', to: 'c4', at: 93 },
  { from: 'b8', to: 'c6', at: 159 },
  { from: 'd1', to: 'h5', at: 183 },
  { from: 'g8', to: 'f6', at: 234 },
  { from: 'h5', to: 'f7', at: 267 },
  // the rewind — back to the position after 3.Qh5
  { from: 'f7', to: 'h5', at: 360, dur: 20, restore: { sq: 'f7', code: 'bP' } },
  { from: 'f6', to: 'g8', at: 360, dur: 20 },
  // the refutation
  { from: 'g7', to: 'g6', at: 510, dur: 12 },
  { from: 'h5', to: 'f3', at: 588 },
  { from: 'g8', to: 'f6', at: 702 },
];

const HIGHLIGHTS: Highlight[] = [
  { sq: 'f7', color: RED, at: 132, until: 350 },
  { sq: 'f6', color: GOLD, at: 237, until: 330 },
  { sq: 'e8', color: RED, at: 279, until: 352 },
  { sq: 'g6', color: GREEN, at: 516, until: 585 },
  { sq: 'f7', color: GOLD, at: 660, until: 706 },
  { sq: 'f6', color: GREEN, at: 714, until: 800 },
  { sq: 'f7', color: GREEN, at: 765, until: 900 },
  { sq: 'c6', color: GREEN, at: 933, until: 1010 },
  { sq: 'f6', color: GREEN, at: 942, until: 1010 },
  { sq: 'g6', color: GREEN, at: 951, until: 1010 },
];

const ARROWS: Arrow[] = [
  { from: 'c4', to: 'f7', color: RED, at: 117, until: 300 },
  { from: 'h5', to: 'f7', color: RED, at: 204, until: 300 },
  { from: 'g6', to: 'h5', color: GREEN, at: 534, until: 585 },
  { from: 'f3', to: 'f7', color: GOLD, at: 645, until: 712 },
  { from: 'd1', to: 'h5', color: GRAY, at: 879, until: 1010, dashed: true },
  { from: 'h5', to: 'f3', color: GRAY, at: 891, until: 1010, dashed: true },
];

// =============================================================================
// HELPER COMPONENTS
// =============================================================================
// Notation chip floating above a square ("Nf6??", "g6!")
const MoveTag: React.FC<{ sq: Sq; text: string; color: string; at: number; until: number }> = ({ sq, text, color, at, until }) => {
  const frame = useCurrentFrame();
  const p = prog(frame, at, at + 9);
  const out = 1 - prog(frame, until - 8, until);
  const o = p * out;
  if (o <= 0.01) return null;
  const c = sqCenter(sq, B.size);
  return (
    <div
      style={{
        position: 'absolute',
        left: B.x + PAD + c.x,
        top: B.y + PAD + c.y - SQ * 0.95,
        transform: `translate(-50%, -50%) scale(${0.7 + 0.3 * p})`,
        opacity: o,
        fontFamily: FONT_MONO,
        fontWeight: 700,
        fontSize: 44,
        color: '#0f1216',
        background: color,
        borderRadius: 12,
        padding: '6px 18px',
        boxShadow: '0 8px 30px rgba(0,0,0,0.5)',
      }}
    >
      {text}
    </div>
  );
};

// Shared hook/loop composition — the loop's last frame lands on the hook's look.
const HookScene: React.FC<{ mode: 'settle' | 'grow'; subtitle: string }> = ({ mode, subtitle }) => {
  const frame = useCurrentFrame();
  const scale =
    mode === 'settle'
      ? 1.06 - 0.06 * EASE_INOUT(prog(frame, 0, 28))
      : 1.0 + 0.06 * EASE_INOUT(prog(frame, 0, 132));
  return (
    <AbsoluteFill style={{ transform: `scale(${scale})` }}>
      <BigTitle
        lines={[
          { text: 'THE 4-MOVE', color: '#ffffff' },
          { text: 'CHECKMATE TRAP', color: GOLD },
        ]}
        subtitle={subtitle}
        warm={mode === 'settle'}
      />
      <ChessBoard
        size={B.size}
        x={B.x}
        y={B.y}
        board={fenBoard(MATE_FEN)}
        highlights={[
          { sq: 'f7', color: RED, at: -8 },
          { sq: 'e8', color: RED, at: -8 },
        ]}
      />
      <Stamp text="CHECKMATE" at={mode === 'settle' ? -6 : 3} x={540} y={945} rotate={-8} />
    </AbsoluteFill>
  );
};

// The persistent board era: trap → rewind → quiz → punish → damage, one timeline.
const MainScene: React.FC = () => {
  const frame = useCurrentFrame();
  const fadeOut = 1 - prog(frame, 1002, 1030);
  return (
    <AbsoluteFill style={{ opacity: fadeOut }}>
      <Kicker text="THE TRAP" at={6} until={330} />
      <Kicker text="FIND THE DEFENSE" color={RED} at={342} until={500} />
      <Kicker text="THE PUNISH" color={GREEN} at={512} until={812} />
      <Kicker text="COUNT THE DAMAGE" at={824} until={1015} />

      <ChessBoard size={B.size} x={B.x} y={B.y} board={fenBoard(START_FEN)} moves={MOVES} highlights={HIGHLIGHTS} arrows={ARROWS} />

      <MoveTag sq="f6" text="Nf6??" color={GOLD} at={240} until={272} />
      <MoveTag sq="g6" text="g6!" color={GREEN} at={518} until={588} />
      <MoveTag sq="f6" text="Nf6!" color={GREEN} at={716} until={800} />

      <Stamp text="CHECKMATE" at={282} until={356} x={540} y={945} />

      <StatChip label="White" value="2 queen moves — 0 threats left" color={RED} x={70} y={280} at={936} />
      <StatChip label="Black" value="3 pieces out — all with tempo" color={GREEN} x={570} y={280} at={948} />

      {/* local frames: global 17.6–19.8s */}
      <Sequence from={432} durationInFrames={66}>
        <PauseCard durSec={2.2} title="PAUSE" subtitle="Black to move — find it" />
      </Sequence>
    </AbsoluteFill>
  );
};

const LoopScene: React.FC = () => {
  const frame = useCurrentFrame();
  return (
    <AbsoluteFill style={{ opacity: prog(frame, 0, 12) }}>
      <HookScene mode="grow" subtitle="now you punish it" />
    </AbsoluteFill>
  );
};

// =============================================================================
// MAIN COMPONENT
// =============================================================================
const Short1Chess: React.FC = () => {
  return (
    <AbsoluteFill style={{ background: '#0f1216' }}>
      <ShortsBackdrop />
      <Sequence from={0} durationInFrames={96}>
        <HookScene mode="settle" subtitle="…and the move that destroys it" />
      </Sequence>
      <Sequence from={96} durationInFrames={1032}>
        <MainScene />
      </Sequence>
      <Sequence from={1122} durationInFrames={138}>
        <LoopScene />
      </Sequence>
      <Captions lines={VO} y={1500} accent={GOLD} />
      <ProgressBar color={GOLD} />
    </AbsoluteFill>
  );
};

export default Short1Chess;
