// AUTO-GENERATED by scripts/gen-registry.mjs — do not edit.
import type React from 'react';
import Shot0, { compositionConfig as cfg0 } from './shots/ai-1/Ai1Door';
import Shot1, { compositionConfig as cfg1 } from './shots/bro-01/Bro01Business';
import Shot2, { compositionConfig as cfg2 } from './shots/short-1/Short1Chess';
import Shot3, { compositionConfig as cfg3 } from './shots/short-10/Short10Fees';
import Shot4, { compositionConfig as cfg4 } from './shots/short-11/Short11Map';
import Shot5, { compositionConfig as cfg5 } from './shots/short-12/Short12Orbit';
import Shot6, { compositionConfig as cfg6 } from './shots/short-13/Short13Water';
import Shot7, { compositionConfig as cfg7 } from './shots/short-14/Short14Seed';
import Shot8, { compositionConfig as cfg8 } from './shots/short-15/Short15Sun';
import Shot9, { compositionConfig as cfg9 } from './shots/short-16/Short16Room';
import Shot10, { compositionConfig as cfg10 } from './shots/short-17/Short17Screen';
import Shot11, { compositionConfig as cfg11 } from './shots/short-18/Short18Blink';
import Shot12, { compositionConfig as cfg12 } from './shots/short-19/Short19Play';
import Shot13, { compositionConfig as cfg13 } from './shots/short-2/Short2Math';
import Shot14, { compositionConfig as cfg14 } from './shots/short-20/Short20Sleep';
import Shot15, { compositionConfig as cfg15 } from './shots/short-21/Short21School';
import Shot16, { compositionConfig as cfg16 } from './shots/short-22/Short22Homework';
import Shot17, { compositionConfig as cfg17 } from './shots/short-23/Short23Bones';
import Shot18, { compositionConfig as cfg18 } from './shots/short-24/Short24Reading';
import Shot19, { compositionConfig as cfg19 } from './shots/short-25/Short25Together';
import Shot20, { compositionConfig as cfg20 } from './shots/short-26/Short26Talk';
import Shot21, { compositionConfig as cfg21 } from './shots/short-27/Short27Pairs';
import Shot22, { compositionConfig as cfg22 } from './shots/short-28/Short28Morning';
import Shot23, { compositionConfig as cfg23 } from './shots/short-29/Short29Mind';
import Shot24, { compositionConfig as cfg24 } from './shots/short-3/Short3Algo';
import Shot25, { compositionConfig as cfg25 } from './shots/short-30/Short30Drink';
import Shot26, { compositionConfig as cfg26 } from './shots/short-31/Short31Start';
import Shot27, { compositionConfig as cfg27 } from './shots/short-32/Short32Identity';
import Shot28, { compositionConfig as cfg28 } from './shots/short-33/Short33Spend';
import Shot29, { compositionConfig as cfg29 } from './shots/short-34/Short34Clutter';
import Shot30, { compositionConfig as cfg30 } from './shots/short-35/Short35Batch';
import Shot31, { compositionConfig as cfg31 } from './shots/short-36/Short36Cool';
import Shot32, { compositionConfig as cfg32 } from './shots/short-37/Short37Reset';
import Shot33, { compositionConfig as cfg33 } from './shots/short-38/Short38Baskets';
import Shot34, { compositionConfig as cfg34 } from './shots/short-39/Short39Doorway';
import Shot35, { compositionConfig as cfg35 } from './shots/short-4/Short4Reflog';
import Shot36, { compositionConfig as cfg36 } from './shots/short-40/Short40Launch';
import Shot37, { compositionConfig as cfg37 } from './shots/short-41/Short41Once';
import Shot38, { compositionConfig as cfg38 } from './shots/short-42/Short42Money';
import Shot39, { compositionConfig as cfg39 } from './shots/short-43/Short43Peruse';
import Shot40, { compositionConfig as cfg40 } from './shots/short-44/Short44Wake';
import Shot41, { compositionConfig as cfg41 } from './shots/short-45/Short45Page';
import Shot42, { compositionConfig as cfg42 } from './shots/short-46/Short46Shower';
import Shot43, { compositionConfig as cfg43 } from './shots/short-47/Short47Autopilot';
import Shot44, { compositionConfig as cfg44 } from './shots/short-48/Short48Gills';
import Shot45, { compositionConfig as cfg45 } from './shots/short-49/Short49Life';
import Shot46, { compositionConfig as cfg46 } from './shots/short-5/Short5Monty';
import Shot47, { compositionConfig as cfg47 } from './shots/short-50/Short50Thunder';
import Shot48, { compositionConfig as cfg48 } from './shots/short-51/Short51Talk';
import Shot49, { compositionConfig as cfg49 } from './shots/short-52/Short52Suns';
import Shot50, { compositionConfig as cfg50 } from './shots/short-53/Short53Borders';
import Shot51, { compositionConfig as cfg51 } from './shots/short-54/Short54Fall';
import Shot52, { compositionConfig as cfg52 } from './shots/short-55/Short55Memory';
import Shot53, { compositionConfig as cfg53 } from './shots/short-56/Short56Freeze';
import Shot54, { compositionConfig as cfg54 } from './shots/short-6/Short6Sheet';
import Shot55, { compositionConfig as cfg55 } from './shots/short-7/Short7Kids';
import Shot56, { compositionConfig as cfg56 } from './shots/short-8/Short8Phish';
import Shot57, { compositionConfig as cfg57 } from './shots/short-9/Short9Chords';
import Shot58, { compositionConfig as cfg58 } from './shots/toon-bro/BroModelSheet';
import Shot59, { compositionConfig as cfg59 } from './shots/vox-1/Vox1Coffee';

export const shots: { Comp: React.FC; config: any }[] = [
  { Comp: Shot0 as React.FC, config: cfg0 },
  { Comp: Shot1 as React.FC, config: cfg1 },
  { Comp: Shot2 as React.FC, config: cfg2 },
  { Comp: Shot3 as React.FC, config: cfg3 },
  { Comp: Shot4 as React.FC, config: cfg4 },
  { Comp: Shot5 as React.FC, config: cfg5 },
  { Comp: Shot6 as React.FC, config: cfg6 },
  { Comp: Shot7 as React.FC, config: cfg7 },
  { Comp: Shot8 as React.FC, config: cfg8 },
  { Comp: Shot9 as React.FC, config: cfg9 },
  { Comp: Shot10 as React.FC, config: cfg10 },
  { Comp: Shot11 as React.FC, config: cfg11 },
  { Comp: Shot12 as React.FC, config: cfg12 },
  { Comp: Shot13 as React.FC, config: cfg13 },
  { Comp: Shot14 as React.FC, config: cfg14 },
  { Comp: Shot15 as React.FC, config: cfg15 },
  { Comp: Shot16 as React.FC, config: cfg16 },
  { Comp: Shot17 as React.FC, config: cfg17 },
  { Comp: Shot18 as React.FC, config: cfg18 },
  { Comp: Shot19 as React.FC, config: cfg19 },
  { Comp: Shot20 as React.FC, config: cfg20 },
  { Comp: Shot21 as React.FC, config: cfg21 },
  { Comp: Shot22 as React.FC, config: cfg22 },
  { Comp: Shot23 as React.FC, config: cfg23 },
  { Comp: Shot24 as React.FC, config: cfg24 },
  { Comp: Shot25 as React.FC, config: cfg25 },
  { Comp: Shot26 as React.FC, config: cfg26 },
  { Comp: Shot27 as React.FC, config: cfg27 },
  { Comp: Shot28 as React.FC, config: cfg28 },
  { Comp: Shot29 as React.FC, config: cfg29 },
  { Comp: Shot30 as React.FC, config: cfg30 },
  { Comp: Shot31 as React.FC, config: cfg31 },
  { Comp: Shot32 as React.FC, config: cfg32 },
  { Comp: Shot33 as React.FC, config: cfg33 },
  { Comp: Shot34 as React.FC, config: cfg34 },
  { Comp: Shot35 as React.FC, config: cfg35 },
  { Comp: Shot36 as React.FC, config: cfg36 },
  { Comp: Shot37 as React.FC, config: cfg37 },
  { Comp: Shot38 as React.FC, config: cfg38 },
  { Comp: Shot39 as React.FC, config: cfg39 },
  { Comp: Shot40 as React.FC, config: cfg40 },
  { Comp: Shot41 as React.FC, config: cfg41 },
  { Comp: Shot42 as React.FC, config: cfg42 },
  { Comp: Shot43 as React.FC, config: cfg43 },
  { Comp: Shot44 as React.FC, config: cfg44 },
  { Comp: Shot45 as React.FC, config: cfg45 },
  { Comp: Shot46 as React.FC, config: cfg46 },
  { Comp: Shot47 as React.FC, config: cfg47 },
  { Comp: Shot48 as React.FC, config: cfg48 },
  { Comp: Shot49 as React.FC, config: cfg49 },
  { Comp: Shot50 as React.FC, config: cfg50 },
  { Comp: Shot51 as React.FC, config: cfg51 },
  { Comp: Shot52 as React.FC, config: cfg52 },
  { Comp: Shot53 as React.FC, config: cfg53 },
  { Comp: Shot54 as React.FC, config: cfg54 },
  { Comp: Shot55 as React.FC, config: cfg55 },
  { Comp: Shot56 as React.FC, config: cfg56 },
  { Comp: Shot57 as React.FC, config: cfg57 },
  { Comp: Shot58 as React.FC, config: cfg58 },
  { Comp: Shot59 as React.FC, config: cfg59 },
];
