// AUTO-GENERATED by scripts/gen-registry.mjs — do not edit.
import type React from 'react';
import Shot0, { compositionConfig as cfg0 } from './shots/ai-1/Ai1Door';
import Shot1, { compositionConfig as cfg1 } from './shots/bro-01/Bro01Business';
import Shot2, { compositionConfig as cfg2 } from './shots/bro-02/Bro025am';
import Shot3, { compositionConfig as cfg3 } from './shots/bro-03/Bro03Gym';
import Shot4, { compositionConfig as cfg4 } from './shots/bro-04/Bro04Cook';
import Shot5, { compositionConfig as cfg5 } from './shots/bro-05/Bro05Crypto';
import Shot6, { compositionConfig as cfg6 } from './shots/bro-06/Bro06Wifi';
import Shot7, { compositionConfig as cfg7 } from './shots/bro-07/Bro07Diet';
import Shot8, { compositionConfig as cfg8 } from './shots/bro-08/Bro08Gps';
import Shot9, { compositionConfig as cfg9 } from './shots/bro-09/Bro09Dj';
import Shot10, { compositionConfig as cfg10 } from './shots/bro-10/Bro10Pigeon';
import Shot11, { compositionConfig as cfg11 } from './shots/bro-11/Bro11Coach';
import Shot12, { compositionConfig as cfg12 } from './shots/bro-12/Bro12Receipt';
import Shot13, { compositionConfig as cfg13 } from './shots/kids-animals-004/KidsAnimals004';
import Shot14, { compositionConfig as cfg14 } from './shots/kids-animals-011/KidsAnimals011';
import Shot15, { compositionConfig as cfg15 } from './shots/kids-animals-018/KidsAnimals018';
import Shot16, { compositionConfig as cfg16 } from './shots/kids-animals-025/KidsAnimals025';
import Shot17, { compositionConfig as cfg17 } from './shots/kids-animals-032/KidsAnimals032';
import Shot18, { compositionConfig as cfg18 } from './shots/kids-heroes/KidsHeroesSheet';
import Shot19, { compositionConfig as cfg19 } from './shots/kids-morals-008/KidsMorals008';
import Shot20, { compositionConfig as cfg20 } from './shots/kids-morals-022/KidsMorals022';
import Shot21, { compositionConfig as cfg21 } from './shots/kids-numbers-002/KidsNumbers002';
import Shot22, { compositionConfig as cfg22 } from './shots/kids-numbers-009/KidsNumbers009';
import Shot23, { compositionConfig as cfg23 } from './shots/kids-numbers-016/KidsNumbers016';
import Shot24, { compositionConfig as cfg24 } from './shots/kids-numbers-023/KidsNumbers023';
import Shot25, { compositionConfig as cfg25 } from './shots/kids-numbers-030/KidsNumbers030';
import Shot26, { compositionConfig as cfg26 } from './shots/kids-puzzles-006/KidsPuzzles006';
import Shot27, { compositionConfig as cfg27 } from './shots/kids-puzzles-013/KidsPuzzles013';
import Shot28, { compositionConfig as cfg28 } from './shots/kids-puzzles-020/KidsPuzzles020';
import Shot29, { compositionConfig as cfg29 } from './shots/kids-puzzles-027/KidsPuzzles027';
import Shot30, { compositionConfig as cfg30 } from './shots/kids-science-005/KidsScience005';
import Shot31, { compositionConfig as cfg31 } from './shots/kids-science-012/KidsScience012';
import Shot32, { compositionConfig as cfg32 } from './shots/kids-science-019/KidsScience019';
import Shot33, { compositionConfig as cfg33 } from './shots/kids-science-026/KidsScience026';
import Shot34, { compositionConfig as cfg34 } from './shots/kids-sheet/KidsChannelBanner';
import Shot35, { compositionConfig as cfg35 } from './shots/kids-sheet/KidsChannelLogo';
import Shot36, { compositionConfig as cfg36 } from './shots/kids-sheet/KidsKitDemo';
import Shot37, { compositionConfig as cfg37 } from './shots/kids-sheet/KidsModelSheet';
import Shot38, { compositionConfig as cfg38 } from './shots/kids-sheet/KidsStyleBoard';
import Shot39, { compositionConfig as cfg39 } from './shots/kids-songs-007/KidsSongs007';
import Shot40, { compositionConfig as cfg40 } from './shots/kids-songs-014/KidsSongs014';
import Shot41, { compositionConfig as cfg41 } from './shots/kids-songs-021/KidsSongs021';
import Shot42, { compositionConfig as cfg42 } from './shots/kids-songs-028/KidsSongs028';
import Shot43, { compositionConfig as cfg43 } from './shots/kids-stories-001/KidsStories001';
import Shot44, { compositionConfig as cfg44 } from './shots/kids-stories-015/KidsStories015';
import Shot45, { compositionConfig as cfg45 } from './shots/kids-stories-029/KidsStories029';
import Shot46, { compositionConfig as cfg46 } from './shots/kids-words-003/KidsWords003';
import Shot47, { compositionConfig as cfg47 } from './shots/kids-words-010/KidsWords010';
import Shot48, { compositionConfig as cfg48 } from './shots/kids-words-017/KidsWords017';
import Shot49, { compositionConfig as cfg49 } from './shots/kids-words-024/KidsWords024';
import Shot50, { compositionConfig as cfg50 } from './shots/kids-words-031/KidsWords031';
import Shot51, { compositionConfig as cfg51 } from './shots/short-1/Short1Chess';
import Shot52, { compositionConfig as cfg52 } from './shots/short-10/Short10Fees';
import Shot53, { compositionConfig as cfg53 } from './shots/short-11/Short11Map';
import Shot54, { compositionConfig as cfg54 } from './shots/short-12/Short12Orbit';
import Shot55, { compositionConfig as cfg55 } from './shots/short-13/Short13Water';
import Shot56, { compositionConfig as cfg56 } from './shots/short-14/Short14Seed';
import Shot57, { compositionConfig as cfg57 } from './shots/short-15/Short15Sun';
import Shot58, { compositionConfig as cfg58 } from './shots/short-16/Short16Room';
import Shot59, { compositionConfig as cfg59 } from './shots/short-17/Short17Screen';
import Shot60, { compositionConfig as cfg60 } from './shots/short-18/Short18Blink';
import Shot61, { compositionConfig as cfg61 } from './shots/short-19/Short19Play';
import Shot62, { compositionConfig as cfg62 } from './shots/short-2/Short2Math';
import Shot63, { compositionConfig as cfg63 } from './shots/short-20/Short20Sleep';
import Shot64, { compositionConfig as cfg64 } from './shots/short-21/Short21School';
import Shot65, { compositionConfig as cfg65 } from './shots/short-22/Short22Homework';
import Shot66, { compositionConfig as cfg66 } from './shots/short-23/Short23Bones';
import Shot67, { compositionConfig as cfg67 } from './shots/short-24/Short24Reading';
import Shot68, { compositionConfig as cfg68 } from './shots/short-25/Short25Together';
import Shot69, { compositionConfig as cfg69 } from './shots/short-26/Short26Talk';
import Shot70, { compositionConfig as cfg70 } from './shots/short-27/Short27Pairs';
import Shot71, { compositionConfig as cfg71 } from './shots/short-28/Short28Morning';
import Shot72, { compositionConfig as cfg72 } from './shots/short-29/Short29Mind';
import Shot73, { compositionConfig as cfg73 } from './shots/short-3/Short3Algo';
import Shot74, { compositionConfig as cfg74 } from './shots/short-30/Short30Drink';
import Shot75, { compositionConfig as cfg75 } from './shots/short-31/Short31Start';
import Shot76, { compositionConfig as cfg76 } from './shots/short-32/Short32Identity';
import Shot77, { compositionConfig as cfg77 } from './shots/short-33/Short33Spend';
import Shot78, { compositionConfig as cfg78 } from './shots/short-34/Short34Clutter';
import Shot79, { compositionConfig as cfg79 } from './shots/short-35/Short35Batch';
import Shot80, { compositionConfig as cfg80 } from './shots/short-36/Short36Cool';
import Shot81, { compositionConfig as cfg81 } from './shots/short-37/Short37Reset';
import Shot82, { compositionConfig as cfg82 } from './shots/short-38/Short38Baskets';
import Shot83, { compositionConfig as cfg83 } from './shots/short-39/Short39Doorway';
import Shot84, { compositionConfig as cfg84 } from './shots/short-4/Short4Reflog';
import Shot85, { compositionConfig as cfg85 } from './shots/short-40/Short40Launch';
import Shot86, { compositionConfig as cfg86 } from './shots/short-41/Short41Once';
import Shot87, { compositionConfig as cfg87 } from './shots/short-42/Short42Money';
import Shot88, { compositionConfig as cfg88 } from './shots/short-43/Short43Peruse';
import Shot89, { compositionConfig as cfg89 } from './shots/short-44/Short44Wake';
import Shot90, { compositionConfig as cfg90 } from './shots/short-45/Short45Page';
import Shot91, { compositionConfig as cfg91 } from './shots/short-46/Short46Shower';
import Shot92, { compositionConfig as cfg92 } from './shots/short-47/Short47Autopilot';
import Shot93, { compositionConfig as cfg93 } from './shots/short-48/Short48Gills';
import Shot94, { compositionConfig as cfg94 } from './shots/short-49/Short49Life';
import Shot95, { compositionConfig as cfg95 } from './shots/short-5/Short5Monty';
import Shot96, { compositionConfig as cfg96 } from './shots/short-50/Short50Thunder';
import Shot97, { compositionConfig as cfg97 } from './shots/short-51/Short51Talk';
import Shot98, { compositionConfig as cfg98 } from './shots/short-52/Short52Suns';
import Shot99, { compositionConfig as cfg99 } from './shots/short-53/Short53Borders';
import Shot100, { compositionConfig as cfg100 } from './shots/short-54/Short54Fall';
import Shot101, { compositionConfig as cfg101 } from './shots/short-55/Short55Memory';
import Shot102, { compositionConfig as cfg102 } from './shots/short-56/Short56Freeze';
import Shot103, { compositionConfig as cfg103 } from './shots/short-6/Short6Sheet';
import Shot104, { compositionConfig as cfg104 } from './shots/short-7/Short7Kids';
import Shot105, { compositionConfig as cfg105 } from './shots/short-8/Short8Phish';
import Shot106, { compositionConfig as cfg106 } from './shots/short-9/Short9Chords';
import Shot107, { compositionConfig as cfg107 } from './shots/toon-bro/BroChannelBanner';
import Shot108, { compositionConfig as cfg108 } from './shots/toon-bro/BroChannelLogo';
import Shot109, { compositionConfig as cfg109 } from './shots/toon-bro/BroModelSheet';
import Shot110, { compositionConfig as cfg110 } from './shots/vox-1/Vox1Coffee';

export const shots: { Comp: React.FC; config: any }[] = [
  { Comp: Shot0 as React.FC, config: cfg0 },
  { Comp: Shot1 as React.FC, config: cfg1 },
  { Comp: Shot2 as React.FC, config: cfg2 },
  { Comp: Shot3 as React.FC, config: cfg3 },
  { Comp: Shot4 as React.FC, config: cfg4 },
  { Comp: Shot5 as React.FC, config: cfg5 },
  { Comp: Shot6 as React.FC, config: cfg6 },
  { Comp: Shot7 as React.FC, config: cfg7 },
  { Comp: Shot8 as React.FC, config: cfg8 },
  { Comp: Shot9 as React.FC, config: cfg9 },
  { Comp: Shot10 as React.FC, config: cfg10 },
  { Comp: Shot11 as React.FC, config: cfg11 },
  { Comp: Shot12 as React.FC, config: cfg12 },
  { Comp: Shot13 as React.FC, config: cfg13 },
  { Comp: Shot14 as React.FC, config: cfg14 },
  { Comp: Shot15 as React.FC, config: cfg15 },
  { Comp: Shot16 as React.FC, config: cfg16 },
  { Comp: Shot17 as React.FC, config: cfg17 },
  { Comp: Shot18 as React.FC, config: cfg18 },
  { Comp: Shot19 as React.FC, config: cfg19 },
  { Comp: Shot20 as React.FC, config: cfg20 },
  { Comp: Shot21 as React.FC, config: cfg21 },
  { Comp: Shot22 as React.FC, config: cfg22 },
  { Comp: Shot23 as React.FC, config: cfg23 },
  { Comp: Shot24 as React.FC, config: cfg24 },
  { Comp: Shot25 as React.FC, config: cfg25 },
  { Comp: Shot26 as React.FC, config: cfg26 },
  { Comp: Shot27 as React.FC, config: cfg27 },
  { Comp: Shot28 as React.FC, config: cfg28 },
  { Comp: Shot29 as React.FC, config: cfg29 },
  { Comp: Shot30 as React.FC, config: cfg30 },
  { Comp: Shot31 as React.FC, config: cfg31 },
  { Comp: Shot32 as React.FC, config: cfg32 },
  { Comp: Shot33 as React.FC, config: cfg33 },
  { Comp: Shot34 as React.FC, config: cfg34 },
  { Comp: Shot35 as React.FC, config: cfg35 },
  { Comp: Shot36 as React.FC, config: cfg36 },
  { Comp: Shot37 as React.FC, config: cfg37 },
  { Comp: Shot38 as React.FC, config: cfg38 },
  { Comp: Shot39 as React.FC, config: cfg39 },
  { Comp: Shot40 as React.FC, config: cfg40 },
  { Comp: Shot41 as React.FC, config: cfg41 },
  { Comp: Shot42 as React.FC, config: cfg42 },
  { Comp: Shot43 as React.FC, config: cfg43 },
  { Comp: Shot44 as React.FC, config: cfg44 },
  { Comp: Shot45 as React.FC, config: cfg45 },
  { Comp: Shot46 as React.FC, config: cfg46 },
  { Comp: Shot47 as React.FC, config: cfg47 },
  { Comp: Shot48 as React.FC, config: cfg48 },
  { Comp: Shot49 as React.FC, config: cfg49 },
  { Comp: Shot50 as React.FC, config: cfg50 },
  { Comp: Shot51 as React.FC, config: cfg51 },
  { Comp: Shot52 as React.FC, config: cfg52 },
  { Comp: Shot53 as React.FC, config: cfg53 },
  { Comp: Shot54 as React.FC, config: cfg54 },
  { Comp: Shot55 as React.FC, config: cfg55 },
  { Comp: Shot56 as React.FC, config: cfg56 },
  { Comp: Shot57 as React.FC, config: cfg57 },
  { Comp: Shot58 as React.FC, config: cfg58 },
  { Comp: Shot59 as React.FC, config: cfg59 },
  { Comp: Shot60 as React.FC, config: cfg60 },
  { Comp: Shot61 as React.FC, config: cfg61 },
  { Comp: Shot62 as React.FC, config: cfg62 },
  { Comp: Shot63 as React.FC, config: cfg63 },
  { Comp: Shot64 as React.FC, config: cfg64 },
  { Comp: Shot65 as React.FC, config: cfg65 },
  { Comp: Shot66 as React.FC, config: cfg66 },
  { Comp: Shot67 as React.FC, config: cfg67 },
  { Comp: Shot68 as React.FC, config: cfg68 },
  { Comp: Shot69 as React.FC, config: cfg69 },
  { Comp: Shot70 as React.FC, config: cfg70 },
  { Comp: Shot71 as React.FC, config: cfg71 },
  { Comp: Shot72 as React.FC, config: cfg72 },
  { Comp: Shot73 as React.FC, config: cfg73 },
  { Comp: Shot74 as React.FC, config: cfg74 },
  { Comp: Shot75 as React.FC, config: cfg75 },
  { Comp: Shot76 as React.FC, config: cfg76 },
  { Comp: Shot77 as React.FC, config: cfg77 },
  { Comp: Shot78 as React.FC, config: cfg78 },
  { Comp: Shot79 as React.FC, config: cfg79 },
  { Comp: Shot80 as React.FC, config: cfg80 },
  { Comp: Shot81 as React.FC, config: cfg81 },
  { Comp: Shot82 as React.FC, config: cfg82 },
  { Comp: Shot83 as React.FC, config: cfg83 },
  { Comp: Shot84 as React.FC, config: cfg84 },
  { Comp: Shot85 as React.FC, config: cfg85 },
  { Comp: Shot86 as React.FC, config: cfg86 },
  { Comp: Shot87 as React.FC, config: cfg87 },
  { Comp: Shot88 as React.FC, config: cfg88 },
  { Comp: Shot89 as React.FC, config: cfg89 },
  { Comp: Shot90 as React.FC, config: cfg90 },
  { Comp: Shot91 as React.FC, config: cfg91 },
  { Comp: Shot92 as React.FC, config: cfg92 },
  { Comp: Shot93 as React.FC, config: cfg93 },
  { Comp: Shot94 as React.FC, config: cfg94 },
  { Comp: Shot95 as React.FC, config: cfg95 },
  { Comp: Shot96 as React.FC, config: cfg96 },
  { Comp: Shot97 as React.FC, config: cfg97 },
  { Comp: Shot98 as React.FC, config: cfg98 },
  { Comp: Shot99 as React.FC, config: cfg99 },
  { Comp: Shot100 as React.FC, config: cfg100 },
  { Comp: Shot101 as React.FC, config: cfg101 },
  { Comp: Shot102 as React.FC, config: cfg102 },
  { Comp: Shot103 as React.FC, config: cfg103 },
  { Comp: Shot104 as React.FC, config: cfg104 },
  { Comp: Shot105 as React.FC, config: cfg105 },
  { Comp: Shot106 as React.FC, config: cfg106 },
  { Comp: Shot107 as React.FC, config: cfg107 },
  { Comp: Shot108 as React.FC, config: cfg108 },
  { Comp: Shot109 as React.FC, config: cfg109 },
  { Comp: Shot110 as React.FC, config: cfg110 },
];
