// AUTO-GENERATED by the Day 31 pack script — line indices into VO.
export const PLAN = {
 "colors": [
  {
   "en": "Apple",
   "fr": "la pomme",
   "hex": "#e63946",
   "obj": "apple",
   "en1": 2,
   "en2": 3,
   "fr1": 4,
   "fr2": 5,
   "say": 6
  },
  {
   "en": "Banana",
   "fr": "la banane",
   "hex": "#ffd60a",
   "obj": "banana",
   "en1": 7,
   "en2": 8,
   "fr1": 9,
   "fr2": 10,
   "say": 11
  },
  {
   "en": "Orange",
   "fr": "l'orange",
   "hex": "#ff924c",
   "obj": "orange",
   "en1": 12,
   "en2": 13,
   "fr1": 14,
   "fr2": 15,
   "say": 16
  },
  {
   "en": "Strawberry",
   "fr": "la fraise",
   "hex": "#ff595e",
   "obj": "strawberry",
   "en1": 17,
   "en2": 18,
   "fr1": 19,
   "fr2": 20,
   "say": 21
  },
  {
   "en": "Grapes",
   "fr": "le raisin",
   "hex": "#7b2cbf",
   "obj": "grapes",
   "en1": 22,
   "en2": 23,
   "fr1": 24,
   "fr2": 25,
   "say": 26
  },
  {
   "en": "Watermelon",
   "fr": "la pastèque",
   "hex": "#52b788",
   "obj": "watermelon",
   "en1": 27,
   "en2": 28,
   "fr1": 29,
   "fr2": 30,
   "say": 31
  }
 ],
 "quiz": [
  {
   "target": 3,
   "options": [
    1,
    3,
    4
   ],
   "correct": 1,
   "ask": 32,
   "ans": 33,
   "ansFr": 34
  }
 ],
 "recapEn": [
  36,
  37
 ],
 "recapFr": [
  39,
  40
 ],
 "bye": 41,
 "byeBobo": 42
} as const;
