// AUTO-GENERATED by tools/gen_voice.py — do not edit.
// Word times are derived from the Kokoro audio's own pauses; captions + lip-sync follow them.
import type { VoLine } from '../../lib/shorts';

export const VO: VoLine[] = [
  { speaker: 'bro', text: 'I\'m done working for other people.', start: 0.2, end: 1.88, words: [{ w: 'I\'m', start: 0.23, end: 0.376 }, { w: 'done', start: 0.376, end: 0.57 }, { w: 'working', start: 0.57, end: 0.911 }, { w: 'for', start: 0.911, end: 1.105 }, { w: 'other', start: 1.105, end: 1.3 }, { w: 'people.', start: 1.3, end: 1.64 }] },
  { speaker: 'dee', text: 'Bro. What\'s the plan?', start: 2.55, end: 3.91, words: [{ w: 'Bro.', start: 2.599, end: 2.933 }, { w: 'What\'s', start: 2.933, end: 3.268 }, { w: 'the', start: 3.268, end: 3.402 }, { w: 'plan?', start: 3.402, end: 3.736 }] },
  { speaker: 'bro', text: 'Trust me. I got this.', start: 4.0, end: 5.25, words: [{ w: 'Trust', start: 4.05, end: 4.339 }, { w: 'me.', start: 4.339, end: 4.532 }, { w: 'I', start: 4.532, end: 4.676 }, { w: 'got', start: 4.676, end: 4.917 }, { w: 'this.', start: 4.917, end: 5.11 }] },
  { speaker: 'bro', text: 'I\'m starting a business.', start: 6.35, end: 7.58, words: [{ w: 'I\'m', start: 6.38, end: 6.523 }, { w: 'starting', start: 6.523, end: 6.953 }, { w: 'a', start: 6.953, end: 7.096 }, { w: 'business.', start: 7.096, end: 7.43 }] },
  { speaker: 'bro', text: 'Entrepreneurship.', start: 9.0, end: 10.02, words: [{ w: 'Entrepreneurship.', start: 9.03, end: 9.91 }] },
  { speaker: 'customer', text: 'How much?', start: 11.7, end: 12.68, words: [{ w: 'How', start: 11.74, end: 12.118 }, { w: 'much?', start: 12.118, end: 12.59 }] },
  { speaker: 'bro', text: 'Ten dollars.', start: 12.8, end: 13.67, words: [{ w: 'Ten', start: 12.83, end: 13.081 }, { w: 'dollars.', start: 13.081, end: 13.52 }] },
  { speaker: 'customer', text: 'It\'s one dollar at the store.', start: 14.35, end: 16.54, words: [{ w: 'It\'s', start: 14.39, end: 14.66 }, { w: 'one', start: 14.66, end: 15.02 }, { w: 'dollar', start: 15.02, end: 15.56 }, { w: 'at', start: 15.56, end: 15.74 }, { w: 'the', start: 15.74, end: 15.92 }, { w: 'store.', start: 15.92, end: 16.46 }] },
  { speaker: 'bro', text: '...Market research.', start: 18.3, end: 19.38, words: [{ w: '...Market', start: 18.33, end: 18.79 }, { w: 'research.', start: 18.79, end: 19.25 }] },
  { speaker: 'dee', text: 'Did you sell anything?', start: 22.4, end: 23.93, words: [{ w: 'Did', start: 22.45, end: 22.703 }, { w: 'you', start: 22.703, end: 22.892 }, { w: 'sell', start: 22.892, end: 23.145 }, { w: 'anything?', start: 23.145, end: 23.65 }] },
  { speaker: 'bro', text: 'I invested in myself.', start: 24.3, end: 25.62, words: [{ w: 'I', start: 24.33, end: 24.485 }, { w: 'invested', start: 24.485, end: 24.951 }, { w: 'in', start: 24.951, end: 25.106 }, { w: 'myself.', start: 25.106, end: 25.52 }] },
  { speaker: 'bro', text: 'I got this.', start: 27.2, end: 28.02, words: [{ w: 'I', start: 27.23, end: 27.4 }, { w: 'got', start: 27.4, end: 27.683 }, { w: 'this.', start: 27.683, end: 27.91 }] },
];
