// AUTO-GENERATED by tools/gen_voice.py — do not edit.
// Word times are derived from the Kokoro audio's own pauses; captions + lip-sync follow them.
import type { VoLine } from '../../lib/shorts';

export const VO: VoLine[] = [
  { speaker: 'mila', text: 'Let\'s count animals, from one to ten!', start: 0.2, end: 2.52, words: [{ w: 'Let\'s', start: 0.23, end: 0.551 }, { w: 'count', start: 0.551, end: 0.935 }, { w: 'animals,', start: 0.935, end: 1.448 }, { w: 'from', start: 1.448, end: 1.705 }, { w: 'one', start: 1.705, end: 1.961 }, { w: 'to', start: 1.961, end: 2.154 }, { w: 'ten!', start: 2.154, end: 2.41 }] },
  { speaker: 'mila', text: 'One lion!', start: 3.02, end: 4.12, words: [{ w: 'One', start: 3.14, end: 3.492 }, { w: 'lion!', start: 3.492, end: 4.02 }] },
  { speaker: 'bobo', text: 'Two piggies!', start: 6.12, end: 6.97, words: [{ w: 'Two', start: 6.14, end: 6.424 }, { w: 'piggies!', start: 6.424, end: 6.85 }] },
  { speaker: 'mila', text: 'Three kittens!', start: 8.97, end: 10.18, words: [{ w: 'Three', start: 9.05, end: 9.509 }, { w: 'kittens!', start: 9.509, end: 10.06 }] },
  { speaker: 'bobo', text: 'Four foxes!', start: 12.28, end: 13.3, words: [{ w: 'Four', start: 12.32, end: 12.655 }, { w: 'foxes!', start: 12.655, end: 13.19 }] },
  { speaker: 'mila', text: 'Five bunnies!', start: 15.5, end: 16.78, words: [{ w: 'Five', start: 15.62, end: 16.079 }, { w: 'bunnies!', start: 16.079, end: 16.63 }] },
  { speaker: 'bobo', text: 'Six little mice!', start: 19.08, end: 20.12, words: [{ w: 'Six', start: 19.11, end: 19.391 }, { w: 'little', start: 19.391, end: 19.729 }, { w: 'mice!', start: 19.729, end: 20.01 }] },
  { speaker: 'mila', text: 'Seven pandas!', start: 22.52, end: 23.78, words: [{ w: 'Seven', start: 22.56, end: 23.072 }, { w: 'pandas!', start: 23.072, end: 23.67 }] },
  { speaker: 'bobo', text: 'Eight owls!', start: 26.28, end: 27.03, words: [{ w: 'Eight', start: 26.32, end: 26.596 }, { w: 'owls!', start: 26.596, end: 26.94 }] },
  { speaker: 'mila', text: 'Nine frogs!', start: 29.63, end: 30.84, words: [{ w: 'Nine', start: 29.69, end: 30.119 }, { w: 'frogs!', start: 30.119, end: 30.72 }] },
  { speaker: 'bobo', text: 'Ten bears... and one is me!', start: 33.54, end: 35.11, words: [{ w: 'Ten', start: 33.57, end: 33.825 }, { w: 'bears...', start: 33.825, end: 34.143 }, { w: 'and', start: 34.143, end: 34.334 }, { w: 'one', start: 34.334, end: 34.588 }, { w: 'is', start: 34.588, end: 34.715 }, { w: 'me!', start: 34.715, end: 34.97 }] },
  { speaker: 'mila', text: 'Now count with me! One, two, three, four, five, six, seven, eight, nine, ten!', start: 37.71, end: 42.36, words: [{ w: 'Now', start: 37.74, end: 38.011 }, { w: 'count', start: 38.011, end: 38.417 }, { w: 'with', start: 38.417, end: 38.62 }, { w: 'me!', start: 38.62, end: 38.89 }, { w: 'One,', start: 38.89, end: 39.161 }, { w: 'two,', start: 39.161, end: 39.431 }, { w: 'three,', start: 39.431, end: 39.77 }, { w: 'four,', start: 39.77, end: 40.108 }, { w: 'five,', start: 40.108, end: 40.446 }, { w: 'six,', start: 40.446, end: 40.785 }, { w: 'seven,', start: 40.785, end: 41.19 }, { w: 'eight,', start: 41.19, end: 41.461 }, { w: 'nine,', start: 41.461, end: 41.799 }, { w: 'ten!', start: 41.799, end: 42.07 }] },
  { speaker: 'mila', text: 'Yay! You can count to ten!', start: 42.96, end: 44.72, words: [{ w: 'Yay!', start: 43.0, end: 43.268 }, { w: 'You', start: 43.268, end: 43.47 }, { w: 'can', start: 43.47, end: 43.738 }, { w: 'count', start: 43.738, end: 44.14 }, { w: 'to', start: 44.14, end: 44.342 }, { w: 'ten!', start: 44.342, end: 44.61 }] },
];
